WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

========== widowx_reacher-v5 ==========
Seed: 0
OrderedDict([('cg_damping', 2.35e-05),
             ('cg_iters', 15),
             ('entcoeff', 9.386438752202742e-07),
             ('gamma', 0.9),
             ('lam', 0.95),
             ('max_kl', 0.0017296927404930307),
             ('n_timesteps', 300000.0),
             ('policy', 'MlpPolicy'),
             ('timesteps_per_batch', 256),
             ('vf_iters', 20),
             ('vf_stepsize', 0.003995018180464256)])
Using 1 environments
Overwriting n_timesteps with n=10000
Creating test environment
TRAINING ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f7c3815f320>
EVAL ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f7c381669b0>
Log path: logs/train_0.01M_widowx_reacher-v5/trpo/widowx_reacher-v5_1
********** Iteration 0 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.153 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.109 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.206          0
         1     0.0713      0.056
         2     0.0212      0.197
         3    0.00616      0.624
         4     0.0011      0.959
         5   0.000964      0.962
         6   0.000143       2.38
         7     0.0422       2.73
         8     0.0135       3.38
         9   0.000182       4.21
        10    0.00246       4.83
        11     0.0184       5.01
        12   3.21e-05       7.83
        13     0.0006       8.08
        14   0.000938        8.1
        15   0.000752       8.17
[35mdone in 0.182 seconds[0m
Expected: 0.030 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.069 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.62        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 2            |
| TimeElapsed             | 0.576        |
| TimestepsSoFar          | 256          |
| entloss                 | 7.997322e-06 |
| entropy                 | 8.5200815    |
| explained_variance_t... | -0.881       |
| meankl                  | 0.0018455756 |
| optimgain               | 0.030274024  |
| surrgain                | 0.030266026  |
------------------------------------------
********** Iteration 1 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.121 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.289          0
         1     0.0541     0.0474
         2     0.0983     0.0925
         3     0.0176       0.17
         4       0.22      0.341
         5      0.013       1.75
         6    0.00931       1.77
         7      0.157       2.17
         8    0.00135       2.43
         9    0.00124       2.43
        10   0.000697       2.55
        11    0.00047       2.55
        12   0.000254       2.63
        13    0.00162       2.67
        14    0.00255       2.73
        15     0.0002       2.74
[35mdone in 0.015 seconds[0m
Expected: 0.032 Actual: 0.035
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.85        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 5            |
| TimeElapsed             | 0.751        |
| TimestepsSoFar          | 512          |
| entloss                 | 8.001915e-06 |
| entropy                 | 8.524975     |
| explained_variance_t... | 0.449        |
| meankl                  | 0.001958685  |
| optimgain               | 0.034754205  |
| surrgain                | 0.034746204  |
------------------------------------------
********** Iteration 2 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.59          0
         1     0.0646     0.0551
         2      0.169      0.114
         3     0.0791      0.451
         4      0.245       0.65
         5     0.0235      0.951
         6     0.0599      0.995
         7    0.00267       1.15
         8    0.00951       1.16
         9    0.00527       1.39
        10    0.00958       1.41
        11    0.00126       1.52
        12     0.0356       1.61
        13    0.00417       1.71
        14     0.0015       2.29
        15     0.0437       2.42
[35mdone in 0.014 seconds[0m
Expected: 0.033 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.89        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 7            |
| TimeElapsed             | 0.907        |
| TimestepsSoFar          | 768          |
| entloss                 | 8.003393e-06 |
| entropy                 | 8.526549     |
| explained_variance_t... | 0.545        |
| meankl                  | 0.0017920984 |
| optimgain               | 0.033620305  |
| surrgain                | 0.033612303  |
------------------------------------------
********** Iteration 3 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.112 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.47          0
         1      0.028     0.0959
         2     0.0601       0.11
         3     0.0142       0.16
         4     0.0294      0.184
         5     0.0155      0.553
         6    0.00691      0.573
         7      0.119       1.06
         8    0.00131       1.32
         9     0.0154       1.42
        10   0.000399       1.45
        11     0.0325       1.71
        12   0.000596        1.8
        13    0.00113       2.01
        14    0.00433       2.06
        15    0.00168       2.09
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.61        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 10           |
| TimeElapsed             | 1.07         |
| TimestepsSoFar          | 1024         |
| entloss                 | 8.007748e-06 |
| entropy                 | 8.531188     |
| explained_variance_t... | 0.632        |
| meankl                  | 0.0016758742 |
| optimgain               | 0.029065048  |
| surrgain                | 0.02905704   |
------------------------------------------
********** Iteration 4 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.331          0
         1     0.0515     0.0511
         2     0.0896      0.113
         3      0.011      0.169
         4     0.0305      0.199
         5    0.00372      0.268
         6    0.00323      0.274
         7    0.00742      0.476
         8    0.00417      0.501
         9    0.00523      0.748
        10   0.000494      0.764
        11    0.00133       1.07
        12     0.0041       1.09
        13   0.000255       1.23
        14    0.00211       1.82
        15    0.00188       1.85
[35mdone in 0.014 seconds[0m
Expected: 0.020 Actual: 0.018
Stepsize OK!
[35mvf[0m
[35mdone in 0.037 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.55        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 12           |
| TimeElapsed             | 1.23         |
| TimestepsSoFar          | 1280         |
| entloss                 | 7.992823e-06 |
| entropy                 | 8.515288     |
| explained_variance_t... | 0.504        |
| meankl                  | 0.001493512  |
| optimgain               | 0.017776685  |
| surrgain                | 0.017768692  |
------------------------------------------
********** Iteration 5 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.09          0
         1     0.0491     0.0863
         2     0.0928      0.117
         3     0.0114      0.174
         4     0.0417      0.197
         5     0.0067      0.378
         6    0.00226      0.385
         7     0.0927      0.838
         8    0.00332       1.12
         9    0.00464       1.49
        10     0.0015       1.51
        11     0.0118       2.94
        12     0.0275       3.04
        13    0.00103       4.74
        14     0.0159       4.86
        15    0.00753       4.97
[35mdone in 0.014 seconds[0m
Expected: 0.031 Actual: 0.040
violated KL constraint. shrinking step.
Expected: 0.031 Actual: 0.018
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -3.52         |
| EpThisIter              | 3             |
| EpisodesSoFar           | 15            |
| TimeElapsed             | 1.38          |
| TimestepsSoFar          | 1536          |
| entloss                 | 7.9918345e-06 |
| entropy                 | 8.514235      |
| explained_variance_t... | 0.626         |
| meankl                  | 0.0007857685  |
| optimgain               | 0.01773064    |
| surrgain                | 0.017722648   |
-------------------------------------------
********** Iteration 6 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.852          0
         1     0.0497     0.0828
         2     0.0684      0.134
         3    0.00992      0.169
         4      0.045      0.194
         5     0.0427       0.59
         6    0.00411      0.632
         7     0.0588      0.728
         8    0.00184       1.01
         9     0.0071       1.03
        10    0.00186       1.37
        11   0.000531       1.77
        12     0.0172       1.86
        13   0.000898       1.94
        14     0.0135       2.01
        15    0.00576       2.14
[35mdone in 0.014 seconds[0m
Expected: 0.027 Actual: 0.027
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.31        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 17           |
| TimeElapsed             | 1.54         |
| TimestepsSoFar          | 1792         |
| entloss                 | 7.969626e-06 |
| entropy                 | 8.490574     |
| explained_variance_t... | 0.87         |
| meankl                  | 0.0018948235 |
| optimgain               | 0.026992658  |
| surrgain                | 0.026984688  |
------------------------------------------
********** Iteration 7 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.705          0
         1     0.0889     0.0691
         2       0.12      0.101
         3      0.018      0.206
         4      0.021      0.221
         5    0.00605      0.286
         6    0.00546      0.293
         7     0.0949      0.528
         8    0.00165      0.825
         9    0.00799      0.884
        10    0.00168      0.906
        11    0.00172        1.1
        12     0.0124       1.16
        13   0.000687       1.19
        14    0.00269       1.38
        15    0.00307       1.86
[35mdone in 0.014 seconds[0m
Expected: 0.025 Actual: 0.021
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.29        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 20           |
| TimeElapsed             | 1.69         |
| TimestepsSoFar          | 2048         |
| entloss                 | 7.969409e-06 |
| entropy                 | 8.490343     |
| explained_variance_t... | 0.658        |
| meankl                  | 0.0014763572 |
| optimgain               | 0.021255363  |
| surrgain                | 0.021247393  |
------------------------------------------
********** Iteration 8 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.562          0
         1     0.0894     0.0638
         2      0.254      0.152
         3     0.0383      0.266
         4     0.0916      0.315
         5    0.00893      0.481
         6     0.0124       0.49
         7     0.0463      0.851
         8    0.00525      0.907
         9     0.0182       1.08
        10   0.000382       1.11
        11   0.000656       1.16
        12     0.0108       1.17
        13   0.000255       1.29
        14     0.0139       1.38
        15    0.00143        1.5
[35mdone in 0.014 seconds[0m
Expected: 0.027 Actual: 0.027
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.18        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 23           |
| TimeElapsed             | 1.84         |
| TimestepsSoFar          | 2304         |
| entloss                 | 7.97756e-06  |
| entropy                 | 8.499027     |
| explained_variance_t... | -0.914       |
| meankl                  | 0.0017537938 |
| optimgain               | 0.026884312  |
| surrgain                | 0.026876334  |
------------------------------------------
********** Iteration 9 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.698          0
         1     0.0458     0.0586
         2     0.0554     0.0786
         3    0.00951      0.132
         4     0.0109      0.141
         5      0.103      0.477
         6     0.0024      0.654
         7     0.0374      0.716
         8   0.000793       1.02
         9     0.0271       1.12
        10   0.000881       1.25
        11     0.0425       1.35
        12   0.000477       1.88
        13    0.00746       2.09
        14    0.00461       2.14
        15   0.000683       2.28
[35mdone in 0.014 seconds[0m
Expected: 0.023 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.09        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 25           |
| TimeElapsed             | 2            |
| TimestepsSoFar          | 2560         |
| entloss                 | 7.960355e-06 |
| entropy                 | 8.480698     |
| explained_variance_t... | 0.459        |
| meankl                  | 0.0020275363 |
| optimgain               | 0.024365824  |
| surrgain                | 0.024357863  |
------------------------------------------
********** Iteration 10 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.105 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.119          0
         1      0.193     0.0586
         2      0.109       0.24
         3     0.0643      0.288
         4     0.0932      0.673
         5    0.00771      0.721
         6     0.0703      0.762
         7     0.0123       1.01
         8    0.00349       1.03
         9     0.0348       1.21
        10    0.00174       1.26
        11    0.00165       1.66
        12     0.0091       1.67
        13    0.00151       1.98
        14      0.012       2.65
        15     0.0247        2.8
[35mdone in 0.014 seconds[0m
Expected: 0.030 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.94        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 28           |
| TimeElapsed             | 2.16         |
| TimestepsSoFar          | 2816         |
| entloss                 | 7.96246e-06  |
| entropy                 | 8.48294      |
| explained_variance_t... | 0.659        |
| meankl                  | 0.0020770838 |
| optimgain               | 0.03018088   |
| surrgain                | 0.030172918  |
------------------------------------------
********** Iteration 11 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.111 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       2.03          0
         1      0.201     0.0857
         2      0.362      0.145
         3     0.0825      0.353
         4     0.0404      0.374
         5     0.0422      0.451
         6     0.0071      0.468
         7      0.112        0.6
         8    0.00989      0.737
         9     0.0175      0.961
        10   0.000924       0.98
        11     0.0015       1.04
        12     0.0381       1.09
        13   0.000566       1.28
        14     0.0205       1.33
        15    0.00246       1.47
[35mdone in 0.014 seconds[0m
Expected: 0.034 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.87        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 30           |
| TimeElapsed             | 2.32         |
| TimestepsSoFar          | 3072         |
| entloss                 | 7.951162e-06 |
| entropy                 | 8.470903     |
| explained_variance_t... | 0.711        |
| meankl                  | 0.0017423546 |
| optimgain               | 0.03382777   |
| surrgain                | 0.03381982   |
------------------------------------------
********** Iteration 12 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.819          0
         1      0.205     0.0688
         2      0.305      0.214
         3     0.0167      0.289
         4     0.0173      0.296
         5    0.00448      0.325
         6    0.00641      0.331
         7     0.0105      0.414
         8    0.00849      0.438
         9    0.00523      0.709
        10      0.063      0.865
        11     0.0128       1.57
        12    0.00351       2.11
        13    0.00228       2.12
        14   0.000558       2.24
        15    0.00431       2.25
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -2.84         |
| EpThisIter              | 3             |
| EpisodesSoFar           | 33            |
| TimeElapsed             | 2.48          |
| TimestepsSoFar          | 3328          |
| entloss                 | 7.9765005e-06 |
| entropy                 | 8.497898      |
| explained_variance_t... | 0.811         |
| meankl                  | 0.0017469546  |
| optimgain               | 0.030081145   |
| surrgain                | 0.03007317    |
-------------------------------------------
********** Iteration 13 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.772          0
         1     0.0525     0.0523
         2      0.092      0.135
         3     0.0117      0.175
         4     0.0516      0.199
         5    0.00423      0.276
         6    0.00659      0.283
         7    0.00845      0.593
         8     0.0217       0.64
         9    0.00218      0.869
        10    0.00137      0.874
        11    0.00209       1.05
        12     0.0148       1.29
        13   0.000945       1.32
        14      0.013       1.36
        15    0.00226       1.51
[35mdone in 0.013 seconds[0m
Expected: 0.022 Actual: 0.023
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.78        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 35           |
| TimeElapsed             | 2.63         |
| TimestepsSoFar          | 3584         |
| entloss                 | 7.982265e-06 |
| entropy                 | 8.50404      |
| explained_variance_t... | 0.238        |
| meankl                  | 0.0017768745 |
| optimgain               | 0.02262677   |
| surrgain                | 0.02261879   |
------------------------------------------
********** Iteration 14 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.099 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       2.47          0
         1     0.0793      0.101
         2     0.0891      0.115
         3      0.087      0.245
         4     0.0408      0.278
         5     0.0886      0.499
         6    0.00719      0.556
         7     0.0948      0.703
         8    0.00225      0.825
         9    0.00359      0.977
        10    0.00129      0.983
        11     0.0013       1.46
        12     0.0381       1.56
        13    0.00229       1.77
        14    0.00348       1.78
        15    0.00105       2.21
[35mdone in 0.014 seconds[0m
Expected: 0.034 Actual: 0.033
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.68        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 38           |
| TimeElapsed             | 2.78         |
| TimestepsSoFar          | 3840         |
| entloss                 | 7.992205e-06 |
| entropy                 | 8.514629     |
| explained_variance_t... | 0.596        |
| meankl                  | 0.0017167614 |
| optimgain               | 0.033298448  |
| surrgain                | 0.033290457  |
------------------------------------------
********** Iteration 15 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.522          0
         1      0.193     0.0689
         2      0.138      0.165
         3    0.00785      0.198
         4     0.0065      0.202
         5     0.0373      0.315
         6     0.0515       0.44
         7     0.0153        1.1
         8     0.0134       1.16
         9    0.00247       1.22
        10     0.0257       1.34
        11     0.0182       1.45
        12    0.00154       1.74
        13    0.00809       1.76
        14    0.00367        1.8
        15    0.00938       2.28
[35mdone in 0.014 seconds[0m
Expected: 0.027 Actual: 0.027
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.64        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 40           |
| TimeElapsed             | 2.93         |
| TimestepsSoFar          | 4096         |
| entloss                 | 7.99755e-06  |
| entropy                 | 8.520324     |
| explained_variance_t... | 0.394        |
| meankl                  | 0.0020339766 |
| optimgain               | 0.02706681   |
| surrgain                | 0.027058812  |
------------------------------------------
********** Iteration 16 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.347          0
         1     0.0687     0.0456
         2     0.0873      0.165
         3     0.0241      0.203
         4      0.254      0.309
         5     0.0337      0.897
         6     0.0437      0.966
         7    0.00228       1.05
         8     0.0124       1.07
         9    0.00884        1.1
        10    0.00814       1.85
        11     0.0207       1.95
        12    0.00382       2.02
        13     0.0553       2.11
        14    0.00422       2.45
        15    0.00942       2.48
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.48        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 43           |
| TimeElapsed             | 3.08         |
| TimestepsSoFar          | 4352         |
| entloss                 | 7.998041e-06 |
| entropy                 | 8.520847     |
| explained_variance_t... | 0.573        |
| meankl                  | 0.001812034  |
| optimgain               | 0.028084975  |
| surrgain                | 0.028076977  |
------------------------------------------
********** Iteration 17 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.563          0
         1     0.0694      0.062
         2      0.103      0.136
         3     0.0147      0.185
         4     0.0695      0.222
         5     0.0259      0.496
         6     0.0211      0.524
         7    0.00988      0.595
         8    0.00519      0.609
         9     0.0114       0.74
        10     0.0651      0.952
        11    0.00236       1.14
        12    0.00325       1.23
        13    0.00202       1.38
        14    0.00227       1.39
        15    0.00635       1.52
[35mdone in 0.013 seconds[0m
Expected: 0.025 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.31        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 46           |
| TimeElapsed             | 3.24         |
| TimestepsSoFar          | 4608         |
| entloss                 | 8.011442e-06 |
| entropy                 | 8.535125     |
| explained_variance_t... | -1.49        |
| meankl                  | 0.0017893636 |
| optimgain               | 0.025264012  |
| surrgain                | 0.025256     |
------------------------------------------
********** Iteration 18 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.92          0
         1     0.0801      0.102
         2       0.18      0.131
         3     0.0409      0.252
         4     0.0718      0.277
         5     0.0129      0.513
         6    0.00283      0.521
         7     0.0484      0.567
         8    0.00268      0.718
         9     0.0278      0.838
        10   0.000455      0.899
        11    0.00289      0.999
        12    0.00131       1.01
        13     0.0424       1.28
        14   0.000806       1.46
        15     0.0088        1.7
[35mdone in 0.013 seconds[0m
Expected: 0.031 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.2         |
| EpThisIter              | 2            |
| EpisodesSoFar           | 48           |
| TimeElapsed             | 3.39         |
| TimestepsSoFar          | 4864         |
| entloss                 | 8.010053e-06 |
| entropy                 | 8.533644     |
| explained_variance_t... | 0.827        |
| meankl                  | 0.0016223146 |
| optimgain               | 0.030812146  |
| surrgain                | 0.030804137  |
------------------------------------------
********** Iteration 19 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.106 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.07          0
         1     0.0987     0.0756
         2      0.182      0.142
         3     0.0212      0.278
         4     0.0552      0.299
         5     0.0256       0.38
         6     0.0163        0.4
         7     0.0255      0.685
         8    0.00822      0.719
         9    0.00323      0.819
        10     0.0112      0.837
        11    0.00597        1.1
        12    0.00131       1.32
        13    0.00871       1.33
        14     0.0105       1.53
        15    0.00353       1.56
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -1.98         |
| EpThisIter              | 3             |
| EpisodesSoFar           | 51            |
| TimeElapsed             | 3.55          |
| TimestepsSoFar          | 5120          |
| entloss                 | 8.0075515e-06 |
| entropy                 | 8.530979      |
| explained_variance_t... | 0.781         |
| meankl                  | 0.0018032712  |
| optimgain               | 0.029119492   |
| surrgain                | 0.029111484   |
-------------------------------------------
********** Iteration 20 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0        1.3          0
         1     0.0929     0.0723
         2     0.0965      0.094
         3     0.0608      0.169
         4     0.0118      0.191
         5     0.0632      0.289
         6    0.00405      0.348
         7     0.0384      0.401
         8    0.00165      0.528
         9      0.013       0.55
        10    0.00133      0.674
        11    0.00455          1
        12    0.00164       1.01
        13     0.0013       1.22
        14    0.00169       1.23
        15   0.000446       1.42
[35mdone in 0.014 seconds[0m
Expected: 0.025 Actual: 0.022
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.91        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 53           |
| TimeElapsed             | 3.7          |
| TimestepsSoFar          | 5376         |
| entloss                 | 7.997523e-06 |
| entropy                 | 8.520295     |
| explained_variance_t... | 0.813        |
| meankl                  | 0.0014327632 |
| optimgain               | 0.021818455  |
| surrgain                | 0.021810457  |
------------------------------------------
********** Iteration 21 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.106 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.745          0
         1      0.122     0.0677
         2      0.455      0.171
         3      0.151      0.463
         4     0.0761       0.51
         5     0.0437       0.67
         6     0.0125      0.689
         7      0.163      0.823
         8    0.00934       1.06
         9     0.0311       1.31
        10    0.00136       1.35
        11    0.00456       1.49
        12     0.0121       1.51
        13    0.00262       2.09
        14    0.00844       2.11
        15    0.00664       2.89
[35mdone in 0.014 seconds[0m
Expected: 0.036 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.78        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 56           |
| TimeElapsed             | 3.86         |
| TimestepsSoFar          | 5632         |
| entloss                 | 7.998449e-06 |
| entropy                 | 8.521282     |
| explained_variance_t... | 0.663        |
| meankl                  | 0.0020086505 |
| optimgain               | 0.034060758  |
| surrgain                | 0.03405276   |
------------------------------------------
********** Iteration 22 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0        1.1          0
         1        0.1     0.0746
         2      0.254      0.137
         3      0.111      0.348
         4     0.0657      0.389
         5       0.15      0.471
         6    0.00361      0.558
         7     0.0387      0.589
         8    0.00409      0.666
         9      0.114      0.985
        10    0.00674       1.34
        11    0.00109       1.73
        12    0.00182       1.73
        13   0.000978       1.78
        14   0.000914       1.78
        15    0.00451       2.15
[35mdone in 0.014 seconds[0m
Expected: 0.032 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.66        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 58           |
| TimeElapsed             | 4.02         |
| TimestepsSoFar          | 5888         |
| entloss                 | 7.996576e-06 |
| entropy                 | 8.519286     |
| explained_variance_t... | 0.393        |
| meankl                  | 0.0015589094 |
| optimgain               | 0.030210963  |
| surrgain                | 0.030202966  |
------------------------------------------
********** Iteration 23 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.87          0
         1     0.0572     0.0728
         2      0.211      0.109
         3     0.0677      0.235
         4     0.0379      0.272
         5     0.0235      0.467
         6     0.0109      0.484
         7     0.0698      0.627
         8    0.00279      0.703
         9      0.024      0.731
        10    0.00391      0.862
        11     0.0851       1.05
        12    0.00293       1.19
        13     0.0159       1.35
        14    0.00313       1.38
        15    0.00221       1.81
[35mdone in 0.014 seconds[0m
Expected: 0.030 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.55        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 61           |
| TimeElapsed             | 4.17         |
| TimestepsSoFar          | 6144         |
| entloss                 | 7.984041e-06 |
| entropy                 | 8.505932     |
| explained_variance_t... | 0.596        |
| meankl                  | 0.001972617  |
| optimgain               | 0.031664964  |
| surrgain                | 0.03165698   |
------------------------------------------
********** Iteration 24 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.23          0
         1     0.0988     0.0634
         2      0.137     0.0995
         3     0.0442      0.188
         4     0.0181      0.201
         5     0.0849      0.387
         6     0.0037      0.456
         7     0.0512      0.533
         8    0.00162      0.639
         9    0.00672      0.702
        10   0.000644      0.712
        11    0.00354      0.844
        12    0.00124      0.851
        13     0.0256      0.965
        14    0.00136       1.06
        15    0.00624        1.9
[35mdone in 0.014 seconds[0m
Expected: 0.026 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.46        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 64           |
| TimeElapsed             | 4.32         |
| TimestepsSoFar          | 6400         |
| entloss                 | 7.993998e-06 |
| entropy                 | 8.51654      |
| explained_variance_t... | 0.884        |
| meankl                  | 0.002092646  |
| optimgain               | 0.028405957  |
| surrgain                | 0.028397962  |
------------------------------------------
********** Iteration 25 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.105 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.45          0
         1      0.155     0.0798
         2      0.197      0.116
         3     0.0643      0.257
         4     0.0479      0.276
         5      0.136      0.453
         6    0.00418      0.539
         7     0.0396      0.564
         8    0.00281      0.771
         9     0.0219      0.978
        10   0.000714       1.02
        11    0.00214        1.1
        12   0.000599        1.1
        13   0.000556       1.16
        14    0.00166       1.16
        15    0.00105       1.29
[35mdone in 0.014 seconds[0m
Expected: 0.030 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.38        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 66           |
| TimeElapsed             | 4.48         |
| TimestepsSoFar          | 6656         |
| entloss                 | 7.998199e-06 |
| entropy                 | 8.521015     |
| explained_variance_t... | 0.836        |
| meankl                  | 0.0017234178 |
| optimgain               | 0.03144703   |
| surrgain                | 0.031439032  |
------------------------------------------
********** Iteration 26 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.21          0
         1      0.262     0.0796
         2      0.365      0.158
         3       0.06      0.345
         4      0.124      0.377
         5      0.122      0.524
         6     0.0095      0.579
         7     0.0782      0.645
         8    0.00371      0.755
         9     0.0137      0.771
        10     0.0015      0.814
        11    0.00165       0.91
        12     0.0228      0.984
        13    0.00236       1.03
        14     0.0399       1.31
        15    0.00498       1.41
[35mdone in 0.013 seconds[0m
Expected: 0.034 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.3         |
| EpThisIter              | 3            |
| EpisodesSoFar           | 69           |
| TimeElapsed             | 4.63         |
| TimestepsSoFar          | 6912         |
| entloss                 | 8.003341e-06 |
| entropy                 | 8.526493     |
| explained_variance_t... | 0.883        |
| meankl                  | 0.001692757  |
| optimgain               | 0.033873033  |
| surrgain                | 0.03386503   |
------------------------------------------
********** Iteration 27 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.195          0
         1       0.32      0.142
         2     0.0425      0.209
         3    0.00928      0.219
         4     0.0397      0.291
         5     0.0213      0.342
         6      0.113      0.467
         7    0.00569      0.627
         8    0.00687      0.641
         9    0.00191      0.673
        10    0.00518      0.681
        11    0.00333      0.942
        12    0.00227       1.02
        13     0.0217       1.22
        14     0.0103       1.28
        15    0.00123       1.71
[35mdone in 0.014 seconds[0m
Expected: 0.024 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.23        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 71           |
| TimeElapsed             | 4.79         |
| TimestepsSoFar          | 7168         |
| entloss                 | 7.978656e-06 |
| entropy                 | 8.500195     |
| explained_variance_t... | -0.641       |
| meankl                  | 0.0019288813 |
| optimgain               | 0.024045942  |
| surrgain                | 0.024037963  |
------------------------------------------
********** Iteration 28 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.813          0
         1      0.222     0.0606
         2     0.0547      0.156
         3     0.0381       0.18
         4      0.049      0.249
         5     0.0583      0.288
         6      0.102      0.506
         7     0.0258       0.63
         8     0.0144      0.716
         9    0.00359      0.732
        10    0.00689      0.759
        11     0.0685      0.876
        12    0.00661       1.18
        13    0.00341       1.25
        14     0.0937       1.37
        15     0.0176       2.47
[35mdone in 0.015 seconds[0m
Expected: 0.030 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.2         |
| EpThisIter              | 3            |
| EpisodesSoFar           | 74           |
| TimeElapsed             | 4.94         |
| TimestepsSoFar          | 7424         |
| entloss                 | 7.966513e-06 |
| entropy                 | 8.487259     |
| explained_variance_t... | 0.7          |
| meankl                  | 0.0022233983 |
| optimgain               | 0.031661086  |
| surrgain                | 0.03165312   |
------------------------------------------
********** Iteration 29 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.557          0
         1      0.139     0.0435
         2      0.225      0.147
         3     0.0405      0.231
         4     0.0399      0.246
         5     0.0961      0.353
         6    0.00442       0.43
         7      0.107      0.759
         8    0.00916      0.934
         9     0.0693       1.12
        10     0.0045       1.27
        11     0.0114       1.64
        12     0.0025       1.65
        13    0.00342        1.8
        14   0.000699        1.8
        15    0.00922       2.03
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.14        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 76           |
| TimeElapsed             | 5.09         |
| TimestepsSoFar          | 7680         |
| entloss                 | 7.985547e-06 |
| entropy                 | 8.507537     |
| explained_variance_t... | -1.91        |
| meankl                  | 0.0016540119 |
| optimgain               | 0.027810233  |
| surrgain                | 0.027802248  |
------------------------------------------
********** Iteration 30 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.099 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.624          0
         1      0.121     0.0439
         2       0.14     0.0842
         3       0.17      0.245
         4     0.0431      0.295
         5      0.161      0.404
         6     0.0168      0.569
         7      0.096      0.633
         8    0.00763      0.956
         9     0.0141        1.1
        10    0.00143       1.12
        11     0.0966       1.21
        12    0.00296       1.41
        13     0.0429       1.57
        14    0.00362       1.65
        15     0.0171       2.36
[35mdone in 0.013 seconds[0m
Expected: 0.030 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.06        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 79           |
| TimeElapsed             | 5.24         |
| TimestepsSoFar          | 7936         |
| entloss                 | 7.983847e-06 |
| entropy                 | 8.505726     |
| explained_variance_t... | 0.643        |
| meankl                  | 0.0019700467 |
| optimgain               | 0.03086466   |
| surrgain                | 0.030856676  |
------------------------------------------
********** Iteration 31 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.542          0
         1      0.263     0.0637
         2      0.288      0.158
         3     0.0352      0.237
         4     0.0242      0.246
         5     0.0742      0.281
         6     0.0293      0.386
         7     0.0584      0.543
         8    0.00326      0.605
         9    0.00771      0.638
        10    0.00518      0.652
        11    0.00466        0.8
        12    0.00154      0.857
        13     0.0323      0.935
        14    0.00286       1.01
        15     0.0121       1.04
[35mdone in 0.014 seconds[0m
Expected: 0.026 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.07        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 81           |
| TimeElapsed             | 5.4          |
| TimestepsSoFar          | 8192         |
| entloss                 | 7.993716e-06 |
| entropy                 | 8.516239     |
| explained_variance_t... | 0.208        |
| meankl                  | 0.0017465174 |
| optimgain               | 0.024470663  |
| surrgain                | 0.024462668  |
------------------------------------------
********** Iteration 32 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       2.07          0
         1      0.414      0.096
         2      0.458      0.178
         3     0.0431      0.361
         4     0.0596      0.374
         5      0.157      0.439
         6     0.0229      0.545
         7     0.0689      0.591
         8    0.00565       0.78
         9     0.0357      0.824
        10       0.01      0.929
        11    0.00409       1.12
        12     0.0276       1.22
        13    0.00567       1.26
        14     0.0513       1.44
        15    0.00548       1.51
[35mdone in 0.014 seconds[0m
Expected: 0.039 Actual: 0.041
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.02        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 84           |
| TimeElapsed             | 5.55         |
| TimestepsSoFar          | 8448         |
| entloss                 | 7.980775e-06 |
| entropy                 | 8.502453     |
| explained_variance_t... | 0.706        |
| meankl                  | 0.001856449  |
| optimgain               | 0.04102639   |
| surrgain                | 0.04101841   |
------------------------------------------
********** Iteration 33 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.107 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.702          0
         1      0.414     0.0642
         2      0.509      0.193
         3     0.0833      0.317
         4      0.024       0.33
         5     0.0697      0.393
         6     0.0103      0.431
         7      0.094      0.498
         8    0.00663      0.679
         9     0.0271       0.75
        10    0.00549      0.792
        11    0.00973      0.975
        12       0.19       1.28
        13    0.00204        1.6
        14     0.0203       1.67
        15    0.00489       1.71
[35mdone in 0.014 seconds[0m
Expected: 0.032 Actual: 0.033
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.982       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 87           |
| TimeElapsed             | 5.71         |
| TimestepsSoFar          | 8704         |
| entloss                 | 7.994041e-06 |
| entropy                 | 8.516585     |
| explained_variance_t... | 0.708        |
| meankl                  | 0.001652892  |
| optimgain               | 0.03278636   |
| surrgain                | 0.032778364  |
------------------------------------------
********** Iteration 34 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.908          0
         1      0.106     0.0442
         2     0.0947     0.0674
         3      0.181       0.18
         4     0.0266      0.237
         5     0.0784      0.286
         6     0.0106      0.406
         7    0.00923      0.416
         8    0.00479      0.585
         9    0.00269      0.593
        10    0.00126      0.752
        11     0.0293       0.78
        12    0.00424      0.994
        13    0.00217          1
        14    0.00107       1.17
        15     0.0237       1.44
[35mdone in 0.014 seconds[0m
Expected: 0.024 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.968       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 89           |
| TimeElapsed             | 5.86         |
| TimestepsSoFar          | 8960         |
| entloss                 | 7.984274e-06 |
| entropy                 | 8.50618      |
| explained_variance_t... | 0.66         |
| meankl                  | 0.001768992  |
| optimgain               | 0.023817597  |
| surrgain                | 0.023809612  |
------------------------------------------
********** Iteration 35 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.107 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.514          0
         1      0.274     0.0707
         2      0.607      0.162
         3     0.0308       0.35
         4      0.115      0.404
         5     0.0326       0.47
         6     0.0187      0.483
         7     0.0779      0.537
         8    0.00843      0.635
         9    0.00218      0.827
        10     0.0186      0.848
        11     0.0167      0.952
        12    0.00644      0.968
        13    0.00659       1.25
        14     0.0114       1.93
        15     0.0129       1.96
[35mdone in 0.014 seconds[0m
Expected: 0.032 Actual: 0.033
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.945       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 92           |
| TimeElapsed             | 6.02         |
| TimestepsSoFar          | 9216         |
| entloss                 | 7.977842e-06 |
| entropy                 | 8.499328     |
| explained_variance_t... | 0.835        |
| meankl                  | 0.0018471    |
| optimgain               | 0.033210065  |
| surrgain                | 0.033202086  |
------------------------------------------
********** Iteration 36 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.107 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.456          0
         1      0.094     0.0539
         2      0.205     0.0904
         3     0.0617      0.239
         4     0.0565      0.274
         5      0.276      0.446
         6     0.0316      0.613
         7     0.0217       0.64
         8     0.0149      0.743
         9    0.00523      0.756
        10     0.0106      0.996
        11     0.0049       1.14
        12     0.0103       1.15
        13    0.00631       1.39
        14     0.0095       1.64
        15    0.00125       1.65
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.913       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 94           |
| TimeElapsed             | 6.18         |
| TimestepsSoFar          | 9472         |
| entloss                 | 7.973374e-06 |
| entropy                 | 8.494567     |
| explained_variance_t... | 0.677        |
| meankl                  | 0.0017949464 |
| optimgain               | 0.027822569  |
| surrgain                | 0.027814595  |
------------------------------------------
********** Iteration 37 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.892          0
         1      0.242     0.0589
         2      0.366      0.121
         3      0.115      0.317
         4     0.0496       0.34
         5      0.134      0.425
         6      0.011      0.504
         7     0.0341      0.524
         8    0.00674      0.617
         9    0.00584      0.625
        10    0.00328      0.688
        11     0.0043        0.8
        12     0.0217      0.821
        13    0.00206      0.925
        14     0.0263      0.956
        15    0.00587       1.48
[35mdone in 0.014 seconds[0m
Expected: 0.031 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.901       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 97           |
| TimeElapsed             | 6.34         |
| TimestepsSoFar          | 9728         |
| entloss                 | 7.974903e-06 |
| entropy                 | 8.496197     |
| explained_variance_t... | 0.682        |
| meankl                  | 0.0018198038 |
| optimgain               | 0.030520432  |
| surrgain                | 0.030512458  |
------------------------------------------
********** Iteration 38 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.110 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.91          0
         1      0.301     0.0774
         2      0.347      0.119
         3      0.352      0.298
         4     0.0697      0.345
         5      0.191      0.395
         6     0.0293      0.675
         7     0.0063      0.686
         8    0.00355      0.947
         9     0.0146       0.96
        10    0.00241       1.24
        11     0.0309       1.26
        12    0.00132       1.48
        13      0.106       1.87
        14    0.00391       2.03
        15     0.0036       2.05
[35mdone in 0.014 seconds[0m
Expected: 0.038 Actual: 0.037
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.876       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 99           |
| TimeElapsed             | 6.5          |
| TimestepsSoFar          | 9984         |
| entloss                 | 7.969367e-06 |
| entropy                 | 8.490299     |
| explained_variance_t... | 0.66         |
| meankl                  | 0.0017133402 |
| optimgain               | 0.03671452   |
| surrgain                | 0.036706552  |
------------------------------------------
********** Iteration 39 ************
Optimizing Policy...
[35msampling[0m
Eval num_timesteps=9984, episode_reward=-2.07 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
[35mdone in 0.378 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.425          0
         1      0.417      0.119
         2      0.252      0.244
         3     0.0257      0.275
         4     0.0726      0.288
         5     0.0499      0.348
         6     0.0582      0.392
         7     0.0526      0.854
         8    0.00619      0.893
         9    0.00971       0.94
        10    0.00499      0.953
        11     0.0111       1.09
        12    0.00139        1.2
        13    0.00539        1.2
        14    0.00121       1.22
        15     0.0233       1.25
[35mdone in 0.014 seconds[0m
Expected: 0.031 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -0.832        |
| EpThisIter              | 3             |
| EpisodesSoFar           | 102           |
| TimeElapsed             | 6.93          |
| TimestepsSoFar          | 10240         |
| entloss                 | 7.9428855e-06 |
| entropy                 | 8.462086      |
| explained_variance_t... | 0.848         |
| meankl                  | 0.0017380363  |
| optimgain               | 0.029971236   |
| surrgain                | 0.029963294   |
-------------------------------------------
/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/callbacks.py:285: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f7c38166da0> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f7c381669b0>
  "{} != {}".format(self.training_env, self.eval_env))
Saving to logs/train_0.01M_widowx_reacher-v5/trpo/widowx_reacher-v5_1
pybullet build time: May 18 2020 02:46:26
