WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

========== widowx_reacher-v5 ==========
Seed: 1
OrderedDict([('cg_damping', 0.01),
             ('cg_iters', 10),
             ('entcoeff', 0.0),
             ('gamma', 0.99),
             ('lam', 0.98),
             ('max_kl', 0.01),
             ('n_timesteps', 10000),
             ('policy', 'MlpPolicy'),
             ('policy_kwargs', 'None'),
             ('timesteps_per_batch', 1024),
             ('vf_iters', 3),
             ('vf_stepsize', 0.0003)])
Using 1 environments
Creating test environment
TRAINING ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f1d3d246518>
EVAL ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f1d3d267860>
Log path: logs/train_10K_widowx_reacher-v5/trpo/widowx_reacher-v5_2
********** Iteration 0 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.501 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.114 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.184          0
         1    0.00713     0.0402
         2     0.0107      0.176
         3    0.00113      0.335
         4    0.00356      0.632
         5   0.000623      0.643
         6   4.02e-05      0.725
         7   0.000213       0.81
         8   2.06e-05      0.811
         9     0.0002      0.823
        10   2.93e-07      0.885
[35mdone in 0.177 seconds[0m
Expected: 0.035 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.054 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.97       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 10          |
| TimeElapsed             | 0.914       |
| TimestepsSoFar          | 1024        |
| entloss                 | 0.0         |
| entropy                 | 8.497448    |
| explained_variance_t... | 0.0782      |
| meankl                  | 0.009192519 |
| optimgain               | 0.0336853   |
| surrgain                | 0.0336853   |
-----------------------------------------
********** Iteration 1 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.416 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.137          0
         1     0.0199     0.0357
         2     0.0381      0.121
         3    0.00693       0.16
         4    0.00647      0.212
         5    0.00178      0.221
         6     0.0011      0.295
         7   0.000959        0.3
         8    0.00149      0.431
         9    0.00438      0.457
        10   9.43e-05      0.591
[35mdone in 0.014 seconds[0m
Expected: 0.031 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.021 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.7        |
| EpThisIter              | 10          |
| EpisodesSoFar           | 20          |
| TimeElapsed             | 1.38        |
| TimestepsSoFar          | 2048        |
| entloss                 | 0.0         |
| entropy                 | 8.502141    |
| explained_variance_t... | 0.207       |
| meankl                  | 0.010149867 |
| optimgain               | 0.032141358 |
| surrgain                | 0.032141358 |
-----------------------------------------
********** Iteration 2 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.405 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.24          0
         1     0.0133     0.0386
         2     0.0145     0.0465
         3    0.00824       0.12
         4     0.0188      0.155
         5    0.00183      0.271
         6    0.00701      0.286
         7   0.000634      0.375
         8    0.00307      0.384
         9    0.00101      0.513
        10     0.0047      0.603
[35mdone in 0.013 seconds[0m
Expected: 0.032 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.021 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.85       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 30          |
| TimeElapsed             | 1.83        |
| TimestepsSoFar          | 3072        |
| entloss                 | 0.0         |
| entropy                 | 8.521862    |
| explained_variance_t... | 0.144       |
| meankl                  | 0.008262515 |
| optimgain               | 0.030621408 |
| surrgain                | 0.030621408 |
-----------------------------------------
********** Iteration 3 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.405 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0     0.0871          0
         1     0.0125     0.0227
         2     0.0299     0.0553
         3    0.00726      0.138
         4     0.0165      0.241
         5    0.00423      0.275
         6    0.00302      0.449
         7     0.0127      0.482
         8    0.00201      0.658
         9     0.0098      0.742
        10   0.000112      0.779
[35mdone in 0.013 seconds[0m
Expected: 0.032 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.021 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.57       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 40          |
| TimeElapsed             | 2.27        |
| TimestepsSoFar          | 4096        |
| entloss                 | 0.0         |
| entropy                 | 8.510563    |
| explained_variance_t... | 0.383       |
| meankl                  | 0.008635818 |
| optimgain               | 0.031714235 |
| surrgain                | 0.031714235 |
-----------------------------------------
********** Iteration 4 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.403 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.101          0
         1     0.0225     0.0259
         2     0.0284     0.0543
         3    0.00315     0.0926
         4     0.0211      0.138
         5     0.0018      0.207
         6    0.00345      0.216
         7     0.0206      0.468
         8    0.00138      0.539
         9    0.00779      0.678
        10   9.93e-05      0.709
[35mdone in 0.013 seconds[0m
Expected: 0.029 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.022 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.33       |
| EpThisIter              | 11          |
| EpisodesSoFar           | 51          |
| TimeElapsed             | 2.72        |
| TimestepsSoFar          | 5120        |
| entloss                 | 0.0         |
| entropy                 | 8.514896    |
| explained_variance_t... | 0.168       |
| meankl                  | 0.009695653 |
| optimgain               | 0.030740183 |
| surrgain                | 0.030740183 |
-----------------------------------------
********** Iteration 5 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.425 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.31          0
         1     0.0264     0.0392
         2     0.0132     0.0459
         3    0.00558     0.0997
         4     0.0087      0.114
         5    0.00939       0.17
         6    0.00149      0.189
         7     0.0135      0.242
         8   0.000881       0.31
         9    0.00584      0.334
        10   0.000202      0.392
[35mdone in 0.013 seconds[0m
Expected: 0.030 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.021 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.15       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 61          |
| TimeElapsed             | 3.19        |
| TimestepsSoFar          | 6144        |
| entloss                 | 0.0         |
| entropy                 | 8.508289    |
| explained_variance_t... | 0.522       |
| meankl                  | 0.009575678 |
| optimgain               | 0.029392818 |
| surrgain                | 0.029392818 |
-----------------------------------------
********** Iteration 6 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.443 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.183          0
         1     0.0221     0.0343
         2     0.0411     0.0615
         3     0.0197      0.126
         4     0.0141      0.148
         5     0.0242       0.27
         6    0.00104      0.308
         7     0.0066       0.32
         8    0.00106      0.383
         9   0.000616      0.387
        10   0.000351      0.466
[35mdone in 0.013 seconds[0m
Expected: 0.032 Actual: 0.033
Stepsize OK!
[35mvf[0m
[35mdone in 0.019 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.75       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 71          |
| TimeElapsed             | 3.68        |
| TimestepsSoFar          | 7168        |
| entloss                 | 0.0         |
| entropy                 | 8.451117    |
| explained_variance_t... | 0.465       |
| meankl                  | 0.009368471 |
| optimgain               | 0.03252915  |
| surrgain                | 0.03252915  |
-----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.434 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.004 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.173          0
         1     0.0554     0.0345
         2      0.103      0.116
         3     0.0134      0.186
         4     0.0254      0.211
         5     0.0113      0.287
         6    0.00907      0.298
         7    0.00857      0.407
         8    0.00305      0.421
         9    0.00311      0.512
        10    0.00188      0.521
[35mdone in 0.015 seconds[0m
Expected: 0.039 Actual: 0.038
Stepsize OK!
[35mvf[0m
[35mdone in 0.020 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.59       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 81          |
| TimeElapsed             | 4.16        |
| TimestepsSoFar          | 8192        |
| entloss                 | 0.0         |
| entropy                 | 8.447707    |
| explained_variance_t... | 0.664       |
| meankl                  | 0.010182013 |
| optimgain               | 0.03849131  |
| surrgain                | 0.03849131  |
-----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.415 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.214          0
         1     0.0311     0.0309
         2      0.031     0.0525
         3     0.0144      0.134
         4     0.0175       0.16
         5     0.0383      0.269
         6     0.0053      0.309
         7     0.0144      0.333
         8      0.013      0.492
         9    0.00305      0.519
        10   0.000907      0.635
[35mdone in 0.014 seconds[0m
Expected: 0.036 Actual: 0.037
Stepsize OK!
[35mvf[0m
[35mdone in 0.022 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.37       |
| EpThisIter              | 11          |
| EpisodesSoFar           | 92          |
| TimeElapsed             | 4.62        |
| TimestepsSoFar          | 9216        |
| entloss                 | 0.0         |
| entropy                 | 8.511398    |
| explained_variance_t... | 0.216       |
| meankl                  | 0.009146504 |
| optimgain               | 0.036574103 |
| surrgain                | 0.036574103 |
-----------------------------------------
********** Iteration 9 ************
Optimizing Policy...
[35msampling[0m
Eval num_timesteps=9216, episode_reward=-1.77 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
[35mdone in 0.712 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.356          0
         1     0.0332     0.0378
         2     0.0375     0.0563
         3     0.0582      0.123
         4    0.00873      0.164
         5    0.00586      0.174
         6    0.00267       0.21
         7    0.00788      0.226
         8     0.0013      0.324
         9    0.00618      0.342
        10   0.000539      0.437
[35mdone in 0.013 seconds[0m
Expected: 0.034 Actual: 0.035
Stepsize OK!
[35mvf[0m
[35mdone in 0.022 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.14       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 102         |
| TimeElapsed             | 5.38        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 8.49474     |
| explained_variance_t... | 0.73        |
| meankl                  | 0.009922656 |
| optimgain               | 0.034832284 |
| surrgain                | 0.034832284 |
-----------------------------------------
/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/callbacks.py:285: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f1d3d267390> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f1d3d267860>
  "{} != {}".format(self.training_env, self.eval_env))
Saving to logs/train_10K_widowx_reacher-v5/trpo/widowx_reacher-v5_2
pybullet build time: May 18 2020 02:46:26
