WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

========== widowx_reacher-v5 ==========
Seed: 0
OrderedDict([('cg_damping', 0.01),
             ('cg_iters', 10),
             ('entcoeff', 0.0),
             ('gamma', 0.99),
             ('lam', 0.98),
             ('max_kl', 0.01),
             ('n_timesteps', 10000),
             ('policy', 'MlpPolicy'),
             ('policy_kwargs', 'None'),
             ('timesteps_per_batch', 1024),
             ('vf_iters', 3),
             ('vf_stepsize', 0.0003)])
Using 1 environments
Creating test environment
TRAINING ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7ff8c402e518>
EVAL ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7ff8c404d860>
Log path: logs/train_10K_widowx_reacher-v5/trpo/widowx_reacher-v5_1
********** Iteration 0 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.480 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.115 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.113          0
         1    0.00429     0.0314
         2    0.00233     0.0655
         3    0.00054      0.346
         4     0.0108      0.449
         5   4.47e-05      0.504
         6   1.56e-05      0.552
         7    0.00149      0.571
         8   0.000252      0.623
         9   1.37e-06      0.648
        10   2.69e-06      0.652
[35mdone in 0.179 seconds[0m
Expected: 0.025 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.053 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.42        |
| EpThisIter              | 10           |
| EpisodesSoFar           | 10           |
| TimeElapsed             | 0.895        |
| TimestepsSoFar          | 1024         |
| entloss                 | 0.0          |
| entropy                 | 8.51202      |
| explained_variance_t... | -0.279       |
| meankl                  | 0.0088769775 |
| optimgain               | 0.024796199  |
| surrgain                | 0.024796199  |
------------------------------------------
********** Iteration 1 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.412 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.123          0
         1    0.00919     0.0334
         2     0.0135     0.0668
         3    0.00355     0.0891
         4    0.00868      0.174
         5   0.000496      0.194
         6    0.00802      0.226
         7   0.000404      0.301
         8    0.00225      0.313
         9   6.56e-05      0.411
        10   0.000393      0.414
[35mdone in 0.013 seconds[0m
Expected: 0.024 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.022 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -2.16       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 20          |
| TimeElapsed             | 1.35        |
| TimestepsSoFar          | 2048        |
| entloss                 | 0.0         |
| entropy                 | 8.531846    |
| explained_variance_t... | 0.132       |
| meankl                  | 0.008740834 |
| optimgain               | 0.024507668 |
| surrgain                | 0.024507668 |
-----------------------------------------
********** Iteration 2 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.413 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.229          0
         1     0.0281      0.047
         2     0.0273     0.0869
         3    0.00218      0.109
         4     0.0221      0.211
         5   0.000439      0.276
         6    0.00291      0.283
         7   0.000192      0.485
         8   0.000319      0.487
         9    0.00187      0.582
        10   0.000228      0.597
[35mdone in 0.013 seconds[0m
Expected: 0.032 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.020 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.98       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 30          |
| TimeElapsed             | 1.81        |
| TimestepsSoFar          | 3072        |
| entloss                 | 0.0         |
| entropy                 | 8.509167    |
| explained_variance_t... | 0.315       |
| meankl                  | 0.009267021 |
| optimgain               | 0.03157404  |
| surrgain                | 0.03157404  |
-----------------------------------------
********** Iteration 3 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.392 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.168          0
         1     0.0102     0.0336
         2     0.0178     0.0585
         3    0.00364     0.0914
         4     0.0127      0.179
         5     0.0015      0.208
         6     0.0121      0.318
         7   0.000165      0.362
         8   0.000366      0.363
         9   0.000197      0.396
        10   0.000429      0.436
[35mdone in 0.013 seconds[0m
Expected: 0.027 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.020 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.87       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 40          |
| TimeElapsed             | 2.24        |
| TimestepsSoFar          | 4096        |
| entloss                 | 0.0         |
| entropy                 | 8.542118    |
| explained_variance_t... | 0.445       |
| meankl                  | 0.009760891 |
| optimgain               | 0.027508866 |
| surrgain                | 0.027508866 |
-----------------------------------------
********** Iteration 4 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.388 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.173          0
         1     0.0198     0.0362
         2     0.0499     0.0807
         3    0.00744      0.163
         4     0.0149      0.202
         5    0.00139      0.228
         6     0.0202      0.271
         7    0.00134      0.398
         8    0.00305       0.41
         9   0.000458      0.486
        10    0.00113      0.491
[35mdone in 0.013 seconds[0m
Expected: 0.032 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.018 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.59       |
| EpThisIter              | 11          |
| EpisodesSoFar           | 51          |
| TimeElapsed             | 2.67        |
| TimestepsSoFar          | 5120        |
| entloss                 | 0.0         |
| entropy                 | 8.548204    |
| explained_variance_t... | 0.575       |
| meankl                  | 0.009394358 |
| optimgain               | 0.032484394 |
| surrgain                | 0.032484394 |
-----------------------------------------
********** Iteration 5 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.405 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.203          0
         1      0.016     0.0367
         2     0.0229     0.0588
         3    0.00469     0.0968
         4     0.0193      0.123
         5    0.00173      0.277
         6    0.00142      0.282
         7    0.00245      0.424
         8   0.000319      0.432
         9     0.0023      0.484
        10      6e-05      0.495
[35mdone in 0.014 seconds[0m
Expected: 0.030 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.019 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.41       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 61          |
| TimeElapsed             | 3.12        |
| TimestepsSoFar          | 6144        |
| entloss                 | 0.0         |
| entropy                 | 8.507433    |
| explained_variance_t... | 0.718       |
| meankl                  | 0.009435279 |
| optimgain               | 0.027837519 |
| surrgain                | 0.027837519 |
-----------------------------------------
********** Iteration 6 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.433 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.245          0
         1     0.0195     0.0339
         2     0.0138      0.044
         3    0.00935       0.11
         4     0.0176      0.136
         5     0.0178      0.291
         6    0.00166      0.324
         7      0.013      0.357
         8   0.000691      0.419
         9    0.00149      0.423
        10   0.000277      0.503
[35mdone in 0.013 seconds[0m
Expected: 0.031 Actual: 0.032
Stepsize OK!
[35mvf[0m
[35mdone in 0.019 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.28       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 71          |
| TimeElapsed             | 3.6         |
| TimestepsSoFar          | 7168        |
| entloss                 | 0.0         |
| entropy                 | 8.522261    |
| explained_variance_t... | 0.613       |
| meankl                  | 0.009501988 |
| optimgain               | 0.03227661  |
| surrgain                | 0.03227661  |
-----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.416 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.004 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.344          0
         1     0.0265     0.0402
         2     0.0198     0.0512
         3     0.0236      0.127
         4      0.013       0.16
         5     0.0316      0.259
         6    0.00161      0.314
         7      0.011      0.354
         8   0.000461      0.396
         9    0.00492      0.413
        10   0.000154      0.459
[35mdone in 0.014 seconds[0m
Expected: 0.035 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.019 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -1.08       |
| EpThisIter              | 10          |
| EpisodesSoFar           | 81          |
| TimeElapsed             | 4.06        |
| TimestepsSoFar          | 8192        |
| entloss                 | 0.0         |
| entropy                 | 8.540282    |
| explained_variance_t... | 0.528       |
| meankl                  | 0.010313059 |
| optimgain               | 0.03424389  |
| surrgain                | 0.03424389  |
-----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.407 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.24          0
         1     0.0288     0.0298
         2     0.0414     0.0503
         3      0.021      0.149
         4     0.0118      0.176
         5     0.0179       0.24
         6    0.00281      0.265
         7     0.0147      0.349
         8    0.00158       0.39
         9    0.00862      0.438
        10   0.000202      0.473
[35mdone in 0.015 seconds[0m
Expected: 0.034 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.021 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -0.883      |
| EpThisIter              | 11          |
| EpisodesSoFar           | 92          |
| TimeElapsed             | 4.51        |
| TimestepsSoFar          | 9216        |
| entloss                 | 0.0         |
| entropy                 | 8.506883    |
| explained_variance_t... | 0.471       |
| meankl                  | 0.010346543 |
| optimgain               | 0.033711676 |
| surrgain                | 0.033711676 |
-----------------------------------------
********** Iteration 9 ************
Optimizing Policy...
[35msampling[0m
Eval num_timesteps=9216, episode_reward=-0.22 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
[35mdone in 0.696 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.003 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.17          0
         1     0.0401     0.0281
         2     0.0294     0.0469
         3     0.0289      0.155
         4     0.0159      0.188
         5    0.00427      0.308
         6     0.0023      0.315
         7    0.00769      0.342
         8    0.00062      0.362
         9    0.00363      0.393
        10    0.00066      0.407
[35mdone in 0.014 seconds[0m
Expected: 0.033 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.021 seconds[0m
-----------------------------------------
| EpLenMean               | 100         |
| EpRewMean               | -0.761      |
| EpThisIter              | 10          |
| EpisodesSoFar           | 102         |
| TimeElapsed             | 5.25        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 8.521122    |
| explained_variance_t... | -0.649      |
| meankl                  | 0.009921231 |
| optimgain               | 0.029906094 |
| surrgain                | 0.029906094 |
-----------------------------------------
/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/callbacks.py:285: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7ff8c404d390> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7ff8c404d860>
  "{} != {}".format(self.training_env, self.eval_env))
Saving to logs/train_10K_widowx_reacher-v5/trpo/widowx_reacher-v5_1
pybullet build time: May 18 2020 02:46:26
