WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/ppo2/ppo2.py:190: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/ppo2/ppo2.py:206: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/ppo2/ppo2.py:242: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

========== widowx_reacher-v5 ==========
Seed: 1
OrderedDict([('cliprange', 0.3),
             ('ent_coef', 0.004507482802317943),
             ('gamma', 0.999),
             ('lam', 0.8),
             ('learning_rate', 0.012856704951056681),
             ('n_envs', 8),
             ('n_steps', 512),
             ('n_timesteps', 1000000.0),
             ('nminibatches', 2),
             ('noptepochs', 20),
             ('normalize', True),
             ('policy', 'MlpPolicy')])
Using 8 environments
Overwriting n_timesteps with n=10000
Normalizing input and reward
Creating test environment
TRAINING ENV TYPE :  <stable_baselines.common.vec_env.vec_normalize.VecNormalize object at 0x7f857bf0e080>
Normalization activated: {'norm_reward': False}
EVAL ENV TYPE :  <stable_baselines.common.vec_env.vec_normalize.VecNormalize object at 0x7f857bf16320>
Log path: logs/train_0.01M_widowx_reacher-v5/ppo2/widowx_reacher-v5_2
-------------------------------------
| approxkl           | 0.056211572  |
| clipfrac           | 0.30056152   |
| ep_len_mean        | 100          |
| ep_reward_mean     | -3           |
| explained_variance | 0.205        |
| fps                | 3942         |
| n_updates          | 1            |
| policy_entropy     | 8.594853     |
| policy_loss        | -0.032167215 |
| serial_timesteps   | 512          |
| time_elapsed       | 1.36e-05     |
| total_timesteps    | 4096         |
| value_loss         | 0.09570043   |
-------------------------------------
-------------------------------------
| approxkl           | 0.09211025   |
| clipfrac           | 0.40046388   |
| ep_len_mean        | 100          |
| ep_reward_mean     | -2.86        |
| explained_variance | 0.734        |
| fps                | 5800         |
| n_updates          | 2            |
| policy_entropy     | 8.48215      |
| policy_loss        | -0.05836314  |
| serial_timesteps   | 1024         |
| time_elapsed       | 1.04         |
| total_timesteps    | 8192         |
| value_loss         | 0.0060939114 |
-------------------------------------
Saving to logs/train_0.01M_widowx_reacher-v5/ppo2/widowx_reacher-v5_2
pybullet build time: May 18 2020 02:46:26
