WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

========== widowx_reacher-v5 ==========
Seed: 1
OrderedDict([('cg_damping', 2.35e-05),
             ('cg_iters', 15),
             ('entcoeff', 9.386438752202742e-07),
             ('gamma', 0.9),
             ('lam', 0.95),
             ('max_kl', 0.0017296927404930307),
             ('n_timesteps', 300000.0),
             ('policy', 'MlpPolicy'),
             ('timesteps_per_batch', 256),
             ('vf_iters', 20),
             ('vf_stepsize', 0.003995018180464256)])
Using 1 environments
Overwriting n_timesteps with n=10000
Creating test environment
TRAINING ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fae2fac6320>
EVAL ENV TYPE :  <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fae2facd9b0>
Log path: logs/train_0.01M_widowx_reacher-v5/trpo/widowx_reacher-v5_2
********** Iteration 0 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.148 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.101 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0     0.0825          0
         1     0.0148      0.028
         2    0.00692      0.102
         3    0.00126      0.802
         4     0.0328      0.953
         5   0.000208       1.04
         6   0.000166       1.77
         7    0.00205       1.78
         8     0.0071       2.13
         9   8.09e-05       3.36
        10     0.0469       6.07
        11    5.3e-05       6.74
        12   3.82e-05       6.82
        13   0.000782       6.87
        14    0.00733       6.98
        15   0.000669       27.4
[35mdone in 0.171 seconds[0m
Expected: 0.028 Actual: 0.027
violated KL constraint. shrinking step.
Expected: 0.028 Actual: 0.014
Stepsize OK!
[35mvf[0m
[35mdone in 0.067 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.92        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 2            |
| TimeElapsed             | 0.549        |
| TimestepsSoFar          | 256          |
| entloss                 | 7.991894e-06 |
| entropy                 | 8.5142975    |
| explained_variance_t... | 0.346        |
| meankl                  | 0.0005650006 |
| optimgain               | 0.0140304025 |
| surrgain                | 0.014022411  |
------------------------------------------
********** Iteration 1 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.099 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.695          0
         1     0.0595     0.0202
         2     0.0222     0.0384
         3      0.016      0.161
         4     0.0684      0.244
         5    0.00635      0.448
         6     0.0305      0.491
         7     0.0838      0.591
         8     0.0051       0.63
         9      0.073      0.857
        10    0.00252       1.09
        11     0.0219       1.38
        12    0.00246       1.43
        13    0.00508       1.44
        14   0.000706       2.32
        15    0.00108        2.6
[35mdone in 0.014 seconds[0m
Expected: 0.023 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.83        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 5            |
| TimeElapsed             | 0.699        |
| TimestepsSoFar          | 512          |
| entloss                 | 7.98538e-06  |
| entropy                 | 8.507359     |
| explained_variance_t... | 0.315        |
| meankl                  | 0.0022512858 |
| optimgain               | 0.025213579  |
| surrgain                | 0.025205594  |
------------------------------------------
********** Iteration 2 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.61          0
         1      0.474     0.0572
         2      0.155     0.0892
         3     0.0292      0.209
         4    0.00828      0.219
         5     0.0163      0.335
         6    0.00852      0.359
         7     0.0156      0.485
         8      0.116      0.539
         9     0.0153      0.833
        10    0.00316      0.864
        11     0.0448       1.09
        12    0.00105       1.23
        13     0.0122       1.35
        14    0.00268       1.36
        15     0.0049       2.85
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -3.14        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 7            |
| TimeElapsed             | 0.854        |
| TimestepsSoFar          | 768          |
| entloss                 | 7.99184e-06  |
| entropy                 | 8.51424      |
| explained_variance_t... | -0.0673      |
| meankl                  | 0.0017575808 |
| optimgain               | 0.027823366  |
| surrgain                | 0.027815374  |
------------------------------------------
********** Iteration 3 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.098 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.33          0
         1     0.0999      0.104
         2      0.273       0.15
         3     0.0586      0.179
         4     0.0112        0.2
         5     0.0116      0.235
         6     0.0218      0.261
         7    0.00388      0.361
         8      0.039      0.459
         9      0.055      0.556
        10    0.00398      0.595
        11    0.00648       1.28
        12    0.00326        1.3
        13    0.00163       1.43
        14      0.143       1.59
        15    0.00205       1.91
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.73        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 10           |
| TimeElapsed             | 1.01         |
| TimestepsSoFar          | 1024         |
| entloss                 | 7.986319e-06 |
| entropy                 | 8.508359     |
| explained_variance_t... | 0.728        |
| meankl                  | 0.0017236078 |
| optimgain               | 0.028248154  |
| surrgain                | 0.028240167  |
------------------------------------------
********** Iteration 4 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.96          0
         1      0.549     0.0508
         2     0.0865     0.0883
         3     0.0406       0.17
         4    0.00518      0.185
         5     0.0112      0.206
         6     0.0206      0.241
         7     0.0109      0.381
         8     0.0116      0.418
         9      0.102      0.519
        10     0.0012      0.616
        11    0.00273      0.624
        12    0.00297      0.851
        13   0.000467       1.01
        14     0.0142       1.03
        15   0.000542       1.06
[35mdone in 0.015 seconds[0m
Expected: 0.023 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.72        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 12           |
| TimeElapsed             | 1.17         |
| TimestepsSoFar          | 1280         |
| entloss                 | 7.986939e-06 |
| entropy                 | 8.509019     |
| explained_variance_t... | 0.586        |
| meankl                  | 0.0017535153 |
| optimgain               | 0.023692496  |
| surrgain                | 0.02368451   |
------------------------------------------
********** Iteration 5 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       2.38          0
         1      0.679      0.049
         2     0.0334     0.0881
         3     0.0647      0.128
         4     0.0145      0.178
         5      0.175      0.383
         6      0.011      0.784
         7    0.00689      0.799
         8      0.121      0.846
         9     0.0174      0.961
        10   0.000778      0.986
        11   0.000435       1.11
        12    0.00401       1.24
        13   0.000171       1.24
        14     0.0083       1.51
        15    0.00046       1.56
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.49        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 15           |
| TimeElapsed             | 1.32         |
| TimestepsSoFar          | 1536         |
| entloss                 | 7.979802e-06 |
| entropy                 | 8.501415     |
| explained_variance_t... | 0.875        |
| meankl                  | 0.0018744583 |
| optimgain               | 0.029271007  |
| surrgain                | 0.029263027  |
------------------------------------------
********** Iteration 6 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.111 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.986          0
         1     0.0691     0.0851
         2      0.146      0.173
         3      0.169      0.212
         4     0.0326      0.252
         5       0.14      0.442
         6    0.00623      0.579
         7    0.00589      0.586
         8    0.00715      0.662
         9     0.0164      0.692
        10     0.0604      0.863
        11    0.00269      0.893
        12    0.00214       1.11
        13   0.000989       1.33
        14     0.0371       1.42
        15     0.0367        1.5
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.027
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -2.3          |
| EpThisIter              | 2             |
| EpisodesSoFar           | 17            |
| TimeElapsed             | 1.49          |
| TimestepsSoFar          | 1792          |
| entloss                 | 7.9658375e-06 |
| entropy                 | 8.486539      |
| explained_variance_t... | 0.792         |
| meankl                  | 0.0016012869  |
| optimgain               | 0.026943924   |
| surrgain                | 0.026935957   |
-------------------------------------------
********** Iteration 7 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.543          0
         1      0.508     0.0472
         2      0.215     0.0956
         3      0.156      0.264
         4      0.055      0.326
         5      0.137       0.66
         6     0.0116      0.737
         7     0.0897      0.802
         8      0.032       1.07
         9     0.0158       1.08
        10     0.0154        1.1
        11    0.00207       1.16
        12   0.000868       1.25
        13    0.00218       1.61
        14     0.0022       1.61
        15     0.0232       1.67
[35mdone in 0.013 seconds[0m
Expected: 0.033 Actual: 0.035
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.2         |
| EpThisIter              | 3            |
| EpisodesSoFar           | 20           |
| TimeElapsed             | 1.64         |
| TimestepsSoFar          | 2048         |
| entloss                 | 7.970325e-06 |
| entropy                 | 8.49132      |
| explained_variance_t... | 0.72         |
| meankl                  | 0.0018445242 |
| optimgain               | 0.034992564  |
| surrgain                | 0.034984592  |
------------------------------------------
********** Iteration 8 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.997          0
         1      0.459     0.0386
         2     0.0502     0.0668
         3      0.104      0.133
         4     0.0164      0.196
         5      0.102      0.287
         6      0.013      0.443
         7     0.0182       0.47
         8      0.045      0.557
         9    0.00352       0.57
        10     0.0482      0.649
        11   0.000899      0.983
        12    0.00139       1.19
        13      0.035       1.22
        14     0.0407       1.47
        15   0.000338       1.61
[35mdone in 0.014 seconds[0m
Expected: 0.025 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.25        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 23           |
| TimeElapsed             | 1.8          |
| TimestepsSoFar          | 2304         |
| entloss                 | 7.954513e-06 |
| entropy                 | 8.474474     |
| explained_variance_t... | 0.598        |
| meankl                  | 0.0017580055 |
| optimgain               | 0.024541436  |
| surrgain                | 0.02453348   |
------------------------------------------
********** Iteration 9 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.17          0
         1      0.659     0.0573
         2     0.0723      0.089
         3     0.0829      0.176
         4      0.017      0.213
         5      0.114      0.299
         6     0.0114      0.504
         7      0.013      0.526
         8     0.0209      0.608
         9    0.00594      0.615
        10     0.0176      0.793
        11    0.00114      0.827
        12    0.00112       0.96
        13      0.134       1.62
        14    0.00711       1.78
        15    0.00105        1.8
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.027
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.19        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 25           |
| TimeElapsed             | 1.95         |
| TimestepsSoFar          | 2560         |
| entloss                 | 7.953205e-06 |
| entropy                 | 8.47308      |
| explained_variance_t... | 0.618        |
| meankl                  | 0.0017087113 |
| optimgain               | 0.02696989   |
| surrgain                | 0.026961936  |
------------------------------------------
********** Iteration 10 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.427          0
         1      0.296     0.0376
         2     0.0558     0.0643
         3     0.0839      0.126
         4     0.0193      0.183
         5     0.0172      0.223
         6    0.00813      0.245
         7    0.00584      0.319
         8     0.0177      0.354
         9     0.0382       0.39
        10     0.0016      0.418
        11    0.00399      0.426
        12    0.00174      0.483
        13    0.00231      0.692
        14     0.0102       0.98
        15    0.00215      0.992
[35mdone in 0.013 seconds[0m
Expected: 0.019 Actual: 0.020
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -2.12         |
| EpThisIter              | 3             |
| EpisodesSoFar           | 28            |
| TimeElapsed             | 2.11          |
| TimestepsSoFar          | 2816          |
| entloss                 | 7.9502615e-06 |
| entropy                 | 8.469944      |
| explained_variance_t... | 0.197         |
| meankl                  | 0.0018913108  |
| optimgain               | 0.019540206   |
| surrgain                | 0.019532256   |
-------------------------------------------
********** Iteration 11 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.41          0
         1      0.349     0.0797
         2     0.0777     0.0911
         3      0.132      0.135
         4     0.0752      0.285
         5     0.0712      0.351
         6     0.0617      0.657
         7     0.0188      0.712
         8      0.017      0.879
         9      0.116      0.943
        10    0.00257      0.985
        11     0.0134          1
        12    0.00278       1.12
        13   0.000929       1.32
        14     0.0555       1.36
        15     0.0157       1.49
[35mdone in 0.014 seconds[0m
Expected: 0.032 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -2.06        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 30           |
| TimeElapsed             | 2.26         |
| TimestepsSoFar          | 3072         |
| entloss                 | 7.945478e-06 |
| entropy                 | 8.464848     |
| explained_variance_t... | 0.746        |
| meankl                  | 0.0017630607 |
| optimgain               | 0.031170728  |
| surrgain                | 0.031162782  |
------------------------------------------
********** Iteration 12 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.45          0
         1       0.53     0.0436
         2      0.188      0.111
         3     0.0976      0.192
         4      0.054      0.242
         5     0.0184      0.304
         6     0.0371      0.337
         7     0.0538      0.519
         8      0.052      0.606
         9      0.419      0.777
        10     0.0153       1.14
        11    0.00558       1.17
        12    0.00702       1.28
        13    0.00153       1.56
        14     0.0255        1.6
        15    0.00148       1.61
[35mdone in 0.013 seconds[0m
Expected: 0.032 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -2.01         |
| EpThisIter              | 3             |
| EpisodesSoFar           | 33            |
| TimeElapsed             | 2.42          |
| TimestepsSoFar          | 3328          |
| entloss                 | 7.9545825e-06 |
| entropy                 | 8.474547      |
| explained_variance_t... | 0.478         |
| meankl                  | 0.0016252205  |
| optimgain               | 0.030790145   |
| surrgain                | 0.03078219    |
-------------------------------------------
********** Iteration 13 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.599          0
         1      0.159     0.0858
         2      0.466      0.135
         3      0.159      0.216
         4     0.0316      0.285
         5     0.0989      0.373
         6     0.0162      0.525
         7      0.138      0.638
         8      0.042      0.974
         9      0.188       1.17
        10     0.0473       1.26
        11     0.0109       1.32
        12    0.00157       1.52
        13    0.00172       1.66
        14     0.0263       1.75
        15     0.0138       1.78
[35mdone in 0.013 seconds[0m
Expected: 0.033 Actual: 0.033
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.97        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 35           |
| TimeElapsed             | 2.57         |
| TimestepsSoFar          | 3584         |
| entloss                 | 7.963205e-06 |
| entropy                 | 8.483733     |
| explained_variance_t... | 0.622        |
| meankl                  | 0.0017444363 |
| optimgain               | 0.03285215   |
| surrgain                | 0.032844186  |
------------------------------------------
********** Iteration 14 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.48          0
         1      0.671     0.0504
         2      0.104     0.0909
         3      0.172      0.187
         4     0.0331      0.265
         5      0.154      0.347
         6     0.0264      0.531
         7    0.00696      0.554
         8     0.0263      0.737
         9     0.0552      0.764
        10     0.0353       0.83
        11    0.00116      0.928
        12   0.000905      0.981
        13    0.00154        1.1
        14    0.00444       1.11
        15     0.0255       1.23
[35mdone in 0.014 seconds[0m
Expected: 0.030 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.86        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 38           |
| TimeElapsed             | 2.72         |
| TimestepsSoFar          | 3840         |
| entloss                 | 7.962789e-06 |
| entropy                 | 8.483291     |
| explained_variance_t... | 0.898        |
| meankl                  | 0.0016814871 |
| optimgain               | 0.029928586  |
| surrgain                | 0.029920623  |
------------------------------------------
********** Iteration 15 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.913          0
         1       0.43     0.0405
         2     0.0443     0.0691
         3      0.105      0.111
         4     0.0252      0.212
         5     0.0559      0.267
         6     0.0364      0.467
         7    0.00865      0.498
         8     0.0278      0.563
         9     0.0194      0.579
        10    0.00283      0.592
        11    0.00122      0.847
        12   0.000808      0.977
        13     0.0271       1.03
        14     0.0527       1.11
        15   0.000488       1.22
[35mdone in 0.014 seconds[0m
Expected: 0.024 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -1.81         |
| EpThisIter              | 2             |
| EpisodesSoFar           | 40            |
| TimeElapsed             | 2.88          |
| TimestepsSoFar          | 4096          |
| entloss                 | 7.9538795e-06 |
| entropy                 | 8.473799      |
| explained_variance_t... | 0.857         |
| meankl                  | 0.0017865952  |
| optimgain               | 0.02443891    |
| surrgain                | 0.024430957   |
-------------------------------------------
********** Iteration 16 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.29          0
         1       0.24     0.0307
         2      0.113     0.0675
         3      0.114      0.164
         4     0.0169      0.209
         5      0.106      0.287
         6     0.0316      0.459
         7    0.00796      0.485
         8     0.0351      0.544
         9     0.0387      0.594
        10    0.00689      0.609
        11   0.000938      0.791
        12   0.000676      0.886
        13      0.011       1.05
        14    0.00355       1.07
        15   0.000591       1.07
[35mdone in 0.013 seconds[0m
Expected: 0.025 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.68        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 43           |
| TimeElapsed             | 3.03         |
| TimestepsSoFar          | 4352         |
| entloss                 | 7.944317e-06 |
| entropy                 | 8.463612     |
| explained_variance_t... | 0.843        |
| meankl                  | 0.0016620569 |
| optimgain               | 0.024419677  |
| surrgain                | 0.024411732  |
------------------------------------------
********** Iteration 17 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.589          0
         1      0.376     0.0428
         2      0.172     0.0782
         3      0.111      0.245
         4     0.0448      0.297
         5      0.139      0.435
         6     0.0155      0.585
         7     0.0172        0.6
         8     0.0208      0.658
         9     0.0107      0.678
        10    0.00929      0.683
        11    0.00322       1.04
        12   0.000702       1.29
        13    0.00927       1.54
        14    0.00378       1.56
        15   0.000764       1.56
[35mdone in 0.013 seconds[0m
Expected: 0.029 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.51        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 46           |
| TimeElapsed             | 3.19         |
| TimestepsSoFar          | 4608         |
| entloss                 | 7.924449e-06 |
| entropy                 | 8.442445     |
| explained_variance_t... | 0.65         |
| meankl                  | 0.0016923621 |
| optimgain               | 0.028800229  |
| surrgain                | 0.028792305  |
------------------------------------------
********** Iteration 18 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.905          0
         1      0.202     0.0293
         2      0.112     0.0664
         3      0.111       0.22
         4     0.0517      0.285
         5      0.214      0.449
         6     0.0319      0.656
         7    0.00515      0.677
         8     0.0569       0.74
         9     0.0464      0.772
        10    0.00533      0.803
        11    0.00105      0.915
        12   0.000872       1.03
        13      0.136       1.27
        14    0.00351       1.46
        15     0.0193       1.53
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.36        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 48           |
| TimeElapsed             | 3.35         |
| TimestepsSoFar          | 4864         |
| entloss                 | 7.909538e-06 |
| entropy                 | 8.4265585    |
| explained_variance_t... | 0.84         |
| meankl                  | 0.0017534106 |
| optimgain               | 0.02827295   |
| surrgain                | 0.02826504   |
------------------------------------------
********** Iteration 19 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.373          0
         1      0.201      0.071
         2      0.678      0.167
         3       0.21      0.267
         4     0.0459      0.331
         5      0.141      0.428
         6     0.0199      0.525
         7     0.0156      0.544
         8     0.0401      0.712
         9    0.00508      0.753
        10     0.0542      0.775
        11    0.00557      0.816
        12     0.0025       1.02
        13   0.000912       1.15
        14    0.00906       1.16
        15    0.00546       1.26
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -1.26         |
| EpThisIter              | 3             |
| EpisodesSoFar           | 51            |
| TimeElapsed             | 3.51          |
| TimestepsSoFar          | 5120          |
| entloss                 | 7.8835565e-06 |
| entropy                 | 8.398879      |
| explained_variance_t... | 0.888         |
| meankl                  | 0.0019115503  |
| optimgain               | 0.029012416   |
| surrgain                | 0.029004533   |
-------------------------------------------
********** Iteration 20 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.101 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.01          0
         1      0.367     0.0421
         2     0.0611     0.0648
         3      0.107      0.121
         4     0.0317      0.205
         5     0.0398      0.234
         6       0.05      0.407
         7    0.00553      0.457
         8     0.0433      0.512
         9     0.0646      0.643
        10    0.00203      0.668
        11    0.00153      0.702
        12   0.000831      0.759
        13    0.00701       1.02
        14    0.00349       1.04
        15    0.00236       1.04
[35mdone in 0.014 seconds[0m
Expected: 0.024 Actual: 0.024
Stepsize OK!
[35mvf[0m
[35mdone in 0.036 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.19        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 53           |
| TimeElapsed             | 3.66         |
| TimestepsSoFar          | 5376         |
| entloss                 | 7.8781e-06   |
| entropy                 | 8.393066     |
| explained_variance_t... | 0.817        |
| meankl                  | 0.0017608469 |
| optimgain               | 0.023713201  |
| surrgain                | 0.023705322  |
------------------------------------------
********** Iteration 21 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.109 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.54          0
         1      0.165     0.0565
         2      0.206     0.0739
         3      0.206      0.154
         4     0.0333      0.258
         5      0.126      0.322
         6     0.0289      0.499
         7    0.00512      0.519
         8     0.0476      0.566
         9    0.00934      0.705
        10      0.101      0.757
        11    0.00271      0.841
        12    0.00199       1.02
        13      0.052       1.19
        14   0.000937       1.32
        15      0.033       1.41
[35mdone in 0.014 seconds[0m
Expected: 0.027 Actual: 0.026
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.14        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 56           |
| TimeElapsed             | 3.82         |
| TimestepsSoFar          | 5632         |
| entloss                 | 7.872039e-06 |
| entropy                 | 8.386608     |
| explained_variance_t... | 0.775        |
| meankl                  | 0.00179528   |
| optimgain               | 0.025931094  |
| surrgain                | 0.025923222  |
------------------------------------------
********** Iteration 22 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.472          0
         1       0.37     0.0369
         2      0.208     0.0833
         3      0.182      0.238
         4     0.0516      0.314
         5      0.189      0.397
         6     0.0427      0.555
         7     0.0097      0.582
         8     0.0128      0.676
         9     0.0497      0.691
        10     0.0281      0.742
        11    0.00387       0.78
        12    0.00454      0.936
        13     0.0028       1.33
        14     0.0101       1.34
        15     0.0245       1.37
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.029
Stepsize OK!
[35mvf[0m
[35mdone in 0.035 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.09        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 58           |
| TimeElapsed             | 3.98         |
| TimestepsSoFar          | 5888         |
| entloss                 | 7.843064e-06 |
| entropy                 | 8.35574      |
| explained_variance_t... | 0.515        |
| meankl                  | 0.0017652591 |
| optimgain               | 0.029407987  |
| surrgain                | 0.029400144  |
------------------------------------------
********** Iteration 23 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.105 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       2.14          0
         1      0.267     0.0371
         2     0.0987     0.0633
         3      0.143      0.151
         4     0.0465      0.232
         5     0.0361      0.255
         6     0.0688      0.427
         7     0.0063      0.487
         8     0.0433       0.53
         9     0.0868       0.57
        10    0.00831      0.631
        11    0.00265      0.747
        12   0.000806      0.842
        13     0.0272      0.926
        14    0.00998      0.967
        15   0.000605      0.975
[35mdone in 0.014 seconds[0m
Expected: 0.026 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -1.05        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 61           |
| TimeElapsed             | 4.14         |
| TimestepsSoFar          | 6144         |
| entloss                 | 7.844413e-06 |
| entropy                 | 8.357177     |
| explained_variance_t... | 0.689        |
| meankl                  | 0.0017435148 |
| optimgain               | 0.024940632  |
| surrgain                | 0.024932789  |
------------------------------------------
********** Iteration 24 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.331          0
         1      0.361     0.0326
         2       0.23      0.124
         3     0.0441      0.299
         4     0.0732      0.326
         5     0.0365      0.401
         6    0.00693      0.419
         7     0.0155      0.429
         8    0.00926      0.483
         9     0.0923      0.626
        10     0.0146      0.671
        11     0.0116      0.716
        12    0.00277       1.03
        13    0.00732       1.39
        14     0.0712       1.74
        15    0.00736       1.89
[35mdone in 0.013 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.899       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 64           |
| TimeElapsed             | 4.29         |
| TimestepsSoFar          | 6400         |
| entloss                 | 7.857893e-06 |
| entropy                 | 8.371538     |
| explained_variance_t... | 0.74         |
| meankl                  | 0.0016922599 |
| optimgain               | 0.027759777  |
| surrgain                | 0.027751919  |
------------------------------------------
********** Iteration 25 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.05          0
         1      0.291     0.0322
         2      0.199     0.0834
         3      0.145      0.189
         4     0.0342      0.239
         5     0.0338      0.257
         6     0.0474      0.428
         7     0.0095      0.473
         8     0.0702      0.651
         9    0.00899      0.674
        10    0.00928      0.696
        11    0.00268      0.737
        12    0.00176      0.795
        13    0.00927      0.966
        14    0.00239      0.982
        15     0.0216      0.999
[35mdone in 0.013 seconds[0m
Expected: 0.026 Actual: 0.026
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.858       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 66           |
| TimeElapsed             | 4.45         |
| TimestepsSoFar          | 6656         |
| entloss                 | 7.817343e-06 |
| entropy                 | 8.328338     |
| explained_variance_t... | 0.58         |
| meankl                  | 0.0017917424 |
| optimgain               | 0.02559427   |
| surrgain                | 0.025586452  |
------------------------------------------
********** Iteration 26 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.303          0
         1      0.365      0.032
         2      0.217      0.111
         3      0.134      0.284
         4      0.051      0.318
         5     0.0295      0.427
         6     0.0138      0.451
         7     0.0105      0.527
         8     0.0472      0.555
         9      0.101      0.601
        10    0.00931      0.678
        11     0.0162      0.707
        12    0.00272      0.818
        13    0.00522       1.21
        14     0.0211       1.24
        15     0.0169       1.64
[35mdone in 0.013 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.81        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 69           |
| TimeElapsed             | 4.6          |
| TimestepsSoFar          | 6912         |
| entloss                 | 7.824218e-06 |
| entropy                 | 8.335662     |
| explained_variance_t... | 0.669        |
| meankl                  | 0.002022193  |
| optimgain               | 0.028208269  |
| surrgain                | 0.028200444  |
------------------------------------------
********** Iteration 27 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.103 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.411          0
         1      0.376     0.0314
         2      0.277      0.122
         3      0.127      0.216
         4      0.035      0.251
         5     0.0633      0.313
         6    0.00594       0.34
         7     0.0189      0.365
         8    0.00458      0.399
         9     0.0678      0.429
        10     0.0146      0.484
        11    0.00697      0.522
        12    0.00299      0.697
        13    0.00195       1.22
        14     0.0103       1.33
        15    0.00258       1.34
[35mdone in 0.013 seconds[0m
Expected: 0.025 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.782       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 71           |
| TimeElapsed             | 4.75         |
| TimestepsSoFar          | 7168         |
| entloss                 | 7.818889e-06 |
| entropy                 | 8.329984     |
| explained_variance_t... | 0.701        |
| meankl                  | 0.0017354537 |
| optimgain               | 0.02515004   |
| surrgain                | 0.02514222   |
------------------------------------------
********** Iteration 28 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.47          0
         1      0.385     0.0408
         2     0.0924       0.06
         3      0.138      0.106
         4      0.132      0.323
         5     0.0673      0.382
         6      0.135      0.586
         7     0.0119      0.695
         8     0.0789      0.763
         9      0.153      0.817
        10    0.00936      0.897
        11    0.00595       1.21
        12     0.0738       1.68
        13    0.00415       1.75
        14      0.276       1.99
        15     0.0275       2.22
[35mdone in 0.013 seconds[0m
Expected: 0.033 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.697       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 74           |
| TimeElapsed             | 4.9          |
| TimestepsSoFar          | 7424         |
| entloss                 | 7.822475e-06 |
| entropy                 | 8.333804     |
| explained_variance_t... | 0.872        |
| meankl                  | 0.0018737062 |
| optimgain               | 0.03399213   |
| surrgain                | 0.033984307  |
------------------------------------------
********** Iteration 29 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       0.39          0
         1      0.203     0.0418
         2      0.148     0.0622
         3      0.132       0.11
         4     0.0412      0.205
         5     0.0289      0.229
         6      0.068      0.302
         7     0.0142      0.404
         8     0.0217      0.599
         9     0.0338      0.671
        10      0.096      0.727
        11    0.00351      0.787
        12    0.00124       0.93
        13     0.0286       1.01
        14    0.00155       1.05
        15     0.0116       1.16
[35mdone in 0.013 seconds[0m
Expected: 0.024 Actual: 0.025
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.679       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 76           |
| TimeElapsed             | 5.05         |
| TimestepsSoFar          | 7680         |
| entloss                 | 7.825598e-06 |
| entropy                 | 8.3371315    |
| explained_variance_t... | 0.568        |
| meankl                  | 0.0018244542 |
| optimgain               | 0.024758877  |
| surrgain                | 0.024751052  |
------------------------------------------
********** Iteration 30 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.105 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.544          0
         1      0.233     0.0477
         2      0.431      0.197
         3      0.583      0.333
         4      0.161      0.396
         5      0.118      0.449
         6     0.0738      0.724
         7     0.0205      0.766
         8     0.0442      0.985
         9    0.00756       1.02
        10     0.0799       1.12
        11    0.00527       1.14
        12    0.00247        1.2
        13     0.0195       1.22
        14   0.000981       1.26
        15      0.014       1.27
[35mdone in 0.014 seconds[0m
Expected: 0.034 Actual: 0.035
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.646       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 79           |
| TimeElapsed             | 5.21         |
| TimestepsSoFar          | 7936         |
| entloss                 | 7.806577e-06 |
| entropy                 | 8.316868     |
| explained_variance_t... | 0.838        |
| meankl                  | 0.0017397394 |
| optimgain               | 0.034870297  |
| surrgain                | 0.03486249   |
------------------------------------------
********** Iteration 31 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.69          0
         1      0.495     0.0431
         2      0.314     0.0726
         3      0.379      0.174
         4     0.0735      0.414
         5      0.183      0.511
         6     0.0491      0.681
         7     0.0222        0.7
         8     0.0492      0.872
         9     0.0145       0.91
        10    0.00984      0.913
        11    0.00164        1.1
        12     0.0175       1.11
        13   0.000776       1.24
        14     0.0108        1.4
        15     0.0022       1.41
[35mdone in 0.014 seconds[0m
Expected: 0.036 Actual: 0.034
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.644       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 81           |
| TimeElapsed             | 5.36         |
| TimestepsSoFar          | 8192         |
| entloss                 | 7.802277e-06 |
| entropy                 | 8.312286     |
| explained_variance_t... | 0.809        |
| meankl                  | 0.0015476982 |
| optimgain               | 0.03364099   |
| surrgain                | 0.033633187  |
------------------------------------------
********** Iteration 32 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.108 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       2.07          0
         1      0.536     0.0599
         2      0.609      0.094
         3      0.335      0.282
         4      0.108      0.391
         5      0.142      0.441
         6     0.0464      0.555
         7     0.0821       0.63
         8     0.0234       0.74
         9      0.262       0.89
        10     0.0117      0.951
        11     0.0154      0.974
        12    0.00891       1.06
        13     0.0113       1.07
        14     0.0102       1.29
        15    0.00619       1.46
[35mdone in 0.014 seconds[0m
Expected: 0.039 Actual: 0.041
Stepsize OK!
[35mvf[0m
[35mdone in 0.033 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.612       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 84           |
| TimeElapsed             | 5.52         |
| TimestepsSoFar          | 8448         |
| entloss                 | 7.788488e-06 |
| entropy                 | 8.297596     |
| explained_variance_t... | 0.867        |
| meankl                  | 0.0018749165 |
| optimgain               | 0.040607926  |
| surrgain                | 0.040600136  |
------------------------------------------
********** Iteration 33 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.108 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.67          0
         1      0.395     0.0422
         2      0.207      0.064
         3      0.145      0.104
         4      0.128      0.215
         5     0.0246      0.257
         6     0.0177      0.367
         7     0.0316       0.42
         8    0.00783      0.466
         9      0.117      0.508
        10     0.0127      0.573
        11    0.00683      0.594
        12     0.0543      0.721
        13    0.00501      0.766
        14     0.0049      0.935
        15    0.00417       1.08
[35mdone in 0.014 seconds[0m
Expected: 0.027 Actual: 0.027
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.596       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 87           |
| TimeElapsed             | 5.68         |
| TimestepsSoFar          | 8704         |
| entloss                 | 7.7718e-06   |
| entropy                 | 8.279817     |
| explained_variance_t... | 0.871        |
| meankl                  | 0.0018444874 |
| optimgain               | 0.026623972  |
| surrgain                | 0.0266162    |
------------------------------------------
********** Iteration 34 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.109 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.769          0
         1      0.487     0.0645
         2      0.469      0.109
         3       0.58      0.176
         4      0.187      0.293
         5     0.0456      0.329
         6     0.0717      0.439
         7    0.00596      0.472
         8     0.0105      0.533
         9    0.00822      0.547
        10     0.0123      0.608
        11    0.00454      0.612
        12    0.00848      0.719
        13    0.00308      0.725
        14    0.00254      0.794
        15     0.0066      0.804
[35mdone in 0.014 seconds[0m
Expected: 0.029 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.591       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 89           |
| TimeElapsed             | 5.84         |
| TimestepsSoFar          | 8960         |
| entloss                 | 7.771511e-06 |
| entropy                 | 8.27951      |
| explained_variance_t... | 0.787        |
| meankl                  | 0.0017327771 |
| optimgain               | 0.03014986   |
| surrgain                | 0.03014209   |
------------------------------------------
********** Iteration 35 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.789          0
         1      0.315     0.0693
         2      0.202      0.089
         3      0.284       0.12
         4      0.188       0.21
         5     0.0321      0.255
         6     0.0312      0.473
         7     0.0159      0.498
         8     0.0383      0.728
         9       0.02      0.785
        10     0.0092      0.944
        11     0.0279      0.953
        12    0.00937       1.14
        13     0.0056       1.15
        14    0.00695       1.33
        15     0.0294       1.37
[35mdone in 0.013 seconds[0m
Expected: 0.030 Actual: 0.030
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.58        |
| EpThisIter              | 3            |
| EpisodesSoFar           | 92           |
| TimeElapsed             | 5.99         |
| TimestepsSoFar          | 9216         |
| entloss                 | 7.77711e-06  |
| entropy                 | 8.285475     |
| explained_variance_t... | 0.461        |
| meankl                  | 0.0017389993 |
| optimgain               | 0.030223338  |
| surrgain                | 0.030215561  |
------------------------------------------
********** Iteration 36 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.100 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.727          0
         1      0.389     0.0347
         2      0.248     0.0742
         3      0.391      0.151
         4      0.193      0.272
         5     0.0417      0.336
         6     0.0223      0.516
         7     0.0085       0.53
         8    0.00557       0.66
         9     0.0114      0.666
        10    0.00644      0.672
        11    0.00192      0.743
        12    0.00353      0.746
        13    0.00177      0.956
        14     0.0197       1.05
        15    0.00139        1.1
[35mdone in 0.013 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.034 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.57        |
| EpThisIter              | 2            |
| EpisodesSoFar           | 94           |
| TimeElapsed             | 6.15         |
| TimestepsSoFar          | 9472         |
| entloss                 | 7.75736e-06  |
| entropy                 | 8.264434     |
| explained_variance_t... | 0.759        |
| meankl                  | 0.0018157826 |
| optimgain               | 0.028063051  |
| surrgain                | 0.028055293  |
------------------------------------------
********** Iteration 37 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.104 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0      0.679          0
         1      0.255      0.034
         2      0.213     0.0615
         3      0.245      0.104
         4      0.219      0.245
         5     0.0418      0.348
         6     0.0695      0.499
         7    0.00732      0.546
         8     0.0498      0.607
         9     0.0023      0.721
        10     0.0542      0.735
        11      0.124      0.968
        12    0.00273       1.06
        13    0.00687       1.28
        14    0.00697        1.3
        15    0.00203       1.62
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.026
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.527       |
| EpThisIter              | 3            |
| EpisodesSoFar           | 97           |
| TimeElapsed             | 6.3          |
| TimestepsSoFar          | 9728         |
| entloss                 | 7.750261e-06 |
| entropy                 | 8.25687      |
| explained_variance_t... | 0.926        |
| meankl                  | 0.0016203406 |
| optimgain               | 0.026439259  |
| surrgain                | 0.026431508  |
------------------------------------------
********** Iteration 38 ************
Optimizing Policy...
[35msampling[0m
[35mdone in 0.102 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.27          0
         1       0.54     0.0635
         2       0.11     0.0993
         3      0.354      0.124
         4      0.117      0.225
         5     0.0327      0.272
         6     0.0644      0.306
         7     0.0119      0.428
         8     0.0232      0.453
         9     0.0166      0.631
        10      0.204      0.728
        11     0.0102      0.861
        12     0.0336       0.88
        13    0.00293       1.08
        14    0.00212       1.13
        15     0.0227       1.49
[35mdone in 0.014 seconds[0m
Expected: 0.030 Actual: 0.031
Stepsize OK!
[35mvf[0m
[35mdone in 0.031 seconds[0m
------------------------------------------
| EpLenMean               | 100          |
| EpRewMean               | -0.533       |
| EpThisIter              | 2            |
| EpisodesSoFar           | 99           |
| TimeElapsed             | 6.45         |
| TimestepsSoFar          | 9984         |
| entloss                 | 7.743528e-06 |
| entropy                 | 8.249698     |
| explained_variance_t... | 0.58         |
| meankl                  | 0.0018718445 |
| optimgain               | 0.031237768  |
| surrgain                | 0.031230025  |
------------------------------------------
********** Iteration 39 ************
Optimizing Policy...
[35msampling[0m
Eval num_timesteps=9984, episode_reward=-0.23 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
[35mdone in 0.377 seconds[0m
[35mcomputegrad[0m
[35mdone in 0.002 seconds[0m
[35mconjugate_gradient[0m
      iter residual norm  soln norm
         0       1.38          0
         1      0.412     0.0357
         2     0.0777     0.0788
         3      0.269      0.107
         4      0.211      0.283
         5     0.0338      0.374
         6     0.0534      0.411
         7     0.0218      0.546
         8      0.036      0.589
         9      0.134      0.741
        10    0.00549      0.776
        11    0.00402       0.86
        12     0.0181      0.868
        13    0.00301      0.953
        14    0.00321       1.06
        15     0.0418       1.09
[35mdone in 0.014 seconds[0m
Expected: 0.028 Actual: 0.028
Stepsize OK!
[35mvf[0m
[35mdone in 0.032 seconds[0m
-------------------------------------------
| EpLenMean               | 100           |
| EpRewMean               | -0.523        |
| EpThisIter              | 3             |
| EpisodesSoFar           | 102           |
| TimeElapsed             | 6.88          |
| TimestepsSoFar          | 10240         |
| entloss                 | 7.7386285e-06 |
| entropy                 | 8.244477      |
| explained_variance_t... | 0.773         |
| meankl                  | 0.0016339542  |
| optimgain               | 0.02822615    |
| surrgain                | 0.02821841    |
-------------------------------------------
/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/18_replab/pierreExeter_github/stable-baselines/stable_baselines/common/callbacks.py:285: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7fae2facdda0> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fae2facd9b0>
  "{} != {}".format(self.training_env, self.eval_env))
Saving to logs/train_0.01M_widowx_reacher-v5/trpo/widowx_reacher-v5_2
pybullet build time: May 18 2020 02:46:26
