Traceback (most recent call last):
  File "2_train.py", line 16, in <module>
    import gym, widowx_env
  File "/home/pierre/.local/lib/python3.6/site-packages/gym/__init__.py", line 10, in <module>
    from gym.spaces import Space
  File "/home/pierre/.local/lib/python3.6/site-packages/gym/spaces/__init__.py", line 1, in <module>
    from gym.spaces.space import Space
  File "/home/pierre/.local/lib/python3.6/site-packages/gym/spaces/space.py", line 1, in <module>
    from gym.utils import seeding
  File "/home/pierre/.local/lib/python3.6/site-packages/gym/utils/seeding.py", line 2, in <module>
    import numpy as np
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/lib/__init__.py", line 9, in <module>
    from .index_tricks import *
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 13, in <module>
    import numpy.matrixlib as matrixlib
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/matrixlib/__init__.py", line 6, in <module>
    from .defmatrix import *
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py", line 13, in <module>
    from numpy.linalg import matrix_power
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/pierre/bin/anaconda3/envs/SB_widowx/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 35, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap>", line 555, in _init_module_attrs
KeyboardInterrupt
