controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    command_joint: gripper_joint
    joints:
      - gripper_joint
