controller_list:
  - name: fake_widowx_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_widowx_gripper_controller
    joints:
      - gripper_joint