--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   n359
  Local device: hfi1_0
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Warning: Open MPI has detected that you are running in an environment with CUDA
devices present and that you are using Intel(r) Ompi-Path networking. However,
the environment variable PSM2_CUDA was not set, meaning that the PSM2 Omni-Path
networking library was not told how to handle CUDA support.

If your application uses CUDA buffers, you should set the environment variable
PSM2_CUDA to 1; otherwise, set it to 0. Setting the variable to the wrong value
can have performance implications on your application, or even cause it to
crash.

Since it was not set, Open MPI has defaulted to setting the PSM2_CUDA
environment variable to 1.

Local hostname: n359
--------------------------------------------------------------------------
/ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

pybullet build time: May 18 2020 02:46:26
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
gripper_aux_linkb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frameb3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
base_linkWARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9a783f0b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9a783f0b00>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9a78414908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9a78414908>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/a2c/a2c.py:158: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py:286: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/a2c/a2c.py:182: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/tensorflow/python/training/rmsprop.py:119: calling Ones.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /ichec/home/users/pierre/.conda/envs/SB_widowx/lib/python3.6/site-packages/stable_baselines/a2c/a2c.py:194: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

========== widowx_reach-v3 ==========
Seed: 0
OrderedDict([('ent_coef', 0.001),
             ('gamma', 0.99),
             ('learning_rate', 0.002),
             ('lr_schedule', 'linear'),
             ('n_envs', 8),
             ('n_steps', 32),
             ('n_timesteps', 1000000.0),
             ('normalize', True),
             ('policy', 'MlpPolicy'),
             ('vf_coef', 0.5)])
Using 8 environments
Overwriting n_timesteps with n=1000000
********goal is : *********** [0.01366778 0.05594924 0.33835924]
********goal is : *********** [-0.02323384  0.05728437  0.26001487]
********goal is : *********** [-0.01792143 -0.12325918  0.33145612]
********goal is : *********** [0.01422341 0.05411843 0.29781762]
********goal is : *********** [0.13076835 0.01228038 0.38644897]
********goal is : *********** [-0.07784191  0.0963904   0.28687349]
********goal is : *********** [ 0.11000084 -0.04368525  0.36675979]
********goal is : *********** [-0.11863368  0.07277889  0.3169932 ]
Normalizing input and reward
TRAINING ENV TYPE 000:  <stable_baselines.common.vec_env.vec_normalize.VecNormalize object at 0x7f9a783e5048>
Creating test environment
TRAINING ENV TYPE 111:  <stable_baselines.common.vec_env.vec_normalize.VecNormalize object at 0x7f9a783e5048>
********goal is : *********** [0.01366778 0.05594924 0.33835924]
Normalization activated: {'norm_reward': False}
PIERRE - CREATE ENV FROM EVALCALLBACK: <stable_baselines.common.vec_env.vec_normalize.VecNormalize object at 0x7f9a783f03c8>
********goal is : *********** [0.01366778 0.05594924 0.33835924]
Normalization activated: {'norm_reward': False}
TRAINING ENV TYPE 444:  <stable_baselines.common.vec_env.vec_normalize.VecNormalize object at 0x7f9a783e5048>
Log path: logs/train_1M_widowx_reach-v3/a2c/widowx_reach-v3_1
---------------------------------
| explained_variance | -0.0375  |
| fps                | 657      |
| nupdates           | 1        |
| policy_entropy     | 8.51     |
| total_timesteps    | 256      |
| value_loss         | 11.7     |
---------------------------------
Eval num_timesteps=10000, episode_reward=-0.54 +/- 0.01
Episode length: 100.00 +/- 0.00
New best mean reward!
Eval num_timesteps=20000, episode_reward=-0.77 +/- 0.01
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.66    |
| explained_variance | -0.0569  |
| fps                | 3357     |
| nupdates           | 100      |
| policy_entropy     | 8.52     |
| total_timesteps    | 25600    |
| value_loss         | 0.635    |
---------------------------------
Eval num_timesteps=30000, episode_reward=-0.65 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=40000, episode_reward=-0.70 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=50000, episode_reward=-0.70 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.68    |
| explained_variance | -0.0746  |
| fps                | 3343     |
| nupdates           | 200      |
| policy_entropy     | 8.52     |
| total_timesteps    | 51200    |
| value_loss         | 0.201    |
---------------------------------
Eval num_timesteps=60000, episode_reward=-0.70 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=70000, episode_reward=-0.59 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.8     |
| explained_variance | 0.0904   |
| fps                | 3389     |
| nupdates           | 300      |
| policy_entropy     | 8.52     |
| total_timesteps    | 76800    |
| value_loss         | 0.458    |
---------------------------------
Eval num_timesteps=80000, episode_reward=-0.39 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
Eval num_timesteps=90000, episode_reward=-0.27 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
Eval num_timesteps=100000, episode_reward=-0.20 +/- 0.00
Episode length: 100.00 +/- 0.00
New best mean reward!
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.69    |
| explained_variance | -0.411   |
| fps                | 3387     |
| nupdates           | 400      |
| policy_entropy     | 8.51     |
| total_timesteps    | 102400   |
| value_loss         | 0.294    |
---------------------------------
Eval num_timesteps=110000, episode_reward=-0.71 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=120000, episode_reward=-0.72 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.69    |
| explained_variance | -0.127   |
| fps                | 3426     |
| nupdates           | 500      |
| policy_entropy     | 8.52     |
| total_timesteps    | 128000   |
| value_loss         | 0.603    |
---------------------------------
Eval num_timesteps=130000, episode_reward=-0.99 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=140000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=150000, episode_reward=-1.48 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.61    |
| explained_variance | -0.1     |
| fps                | 3425     |
| nupdates           | 600      |
| policy_entropy     | 8.55     |
| total_timesteps    | 153600   |
| value_loss         | 0.684    |
---------------------------------
Eval num_timesteps=160000, episode_reward=-1.50 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=170000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.59    |
| explained_variance | -0.647   |
| fps                | 3449     |
| nupdates           | 700      |
| policy_entropy     | 8.58     |
| total_timesteps    | 179200   |
| value_loss         | 0.861    |
---------------------------------
Eval num_timesteps=180000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=190000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=200000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.62    |
| explained_variance | -2.34    |
| fps                | 3442     |
| nupdates           | 800      |
| policy_entropy     | 8.54     |
| total_timesteps    | 204800   |
| value_loss         | 0.984    |
---------------------------------
Eval num_timesteps=210000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=220000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=230000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.8     |
| ep_reward_mean     | -1.54    |
| explained_variance | 0.228    |
| fps                | 3440     |
| nupdates           | 900      |
| policy_entropy     | 8.53     |
| total_timesteps    | 230400   |
| value_loss         | 0.432    |
---------------------------------
Eval num_timesteps=240000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=250000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.6     |
| ep_reward_mean     | -1.53    |
| explained_variance | -0.266   |
| fps                | 3456     |
| nupdates           | 1000     |
| policy_entropy     | 8.51     |
| total_timesteps    | 256000   |
| value_loss         | 0.697    |
---------------------------------
Eval num_timesteps=260000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=270000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=280000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.2     |
| ep_reward_mean     | -1.5     |
| explained_variance | 0.507    |
| fps                | 3451     |
| nupdates           | 1100     |
| policy_entropy     | 8.5      |
| total_timesteps    | 281600   |
| value_loss         | 0.279    |
---------------------------------
Eval num_timesteps=290000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=300000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.5     |
| explained_variance | 0.641    |
| fps                | 3463     |
| nupdates           | 1200     |
| policy_entropy     | 8.47     |
| total_timesteps    | 307200   |
| value_loss         | 0.192    |
---------------------------------
Eval num_timesteps=310000, episode_reward=-0.54 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=320000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=330000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 98.9     |
| ep_reward_mean     | -1.46    |
| explained_variance | 0.598    |
| fps                | 3460     |
| nupdates           | 1300     |
| policy_entropy     | 8.47     |
| total_timesteps    | 332800   |
| value_loss         | 0.319    |
---------------------------------
Eval num_timesteps=340000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=350000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.41    |
| explained_variance | 0.695    |
| fps                | 3471     |
| nupdates           | 1400     |
| policy_entropy     | 8.46     |
| total_timesteps    | 358400   |
| value_loss         | 0.167    |
---------------------------------
Eval num_timesteps=360000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=370000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=380000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.3     |
| ep_reward_mean     | -1.47    |
| explained_variance | 0.661    |
| fps                | 3466     |
| nupdates           | 1500     |
| policy_entropy     | 8.51     |
| total_timesteps    | 384000   |
| value_loss         | 0.223    |
---------------------------------
Eval num_timesteps=390000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=400000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.53    |
| explained_variance | 0.338    |
| fps                | 3474     |
| nupdates           | 1600     |
| policy_entropy     | 8.53     |
| total_timesteps    | 409600   |
| value_loss         | 0.421    |
---------------------------------
Eval num_timesteps=410000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=420000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=430000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.52    |
| explained_variance | 0.604    |
| fps                | 3468     |
| nupdates           | 1700     |
| policy_entropy     | 8.5      |
| total_timesteps    | 435200   |
| value_loss         | 0.164    |
---------------------------------
Eval num_timesteps=440000, episode_reward=-0.48 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=450000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=460000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.51    |
| explained_variance | 0.592    |
| fps                | 3460     |
| nupdates           | 1800     |
| policy_entropy     | 8.52     |
| total_timesteps    | 460800   |
| value_loss         | 0.132    |
---------------------------------
Eval num_timesteps=470000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=480000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.47    |
| explained_variance | 0.547    |
| fps                | 3455     |
| nupdates           | 1900     |
| policy_entropy     | 8.48     |
| total_timesteps    | 486400   |
| value_loss         | 0.157    |
---------------------------------
Eval num_timesteps=490000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=500000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=510000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.48    |
| explained_variance | 0.593    |
| fps                | 3452     |
| nupdates           | 2000     |
| policy_entropy     | 8.49     |
| total_timesteps    | 512000   |
| value_loss         | 0.151    |
---------------------------------
Eval num_timesteps=520000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=530000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.46    |
| explained_variance | 0.647    |
| fps                | 3460     |
| nupdates           | 2100     |
| policy_entropy     | 8.52     |
| total_timesteps    | 537600   |
| value_loss         | 0.11     |
---------------------------------
Eval num_timesteps=540000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=550000, episode_reward=-0.50 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=560000, episode_reward=-0.50 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.48    |
| explained_variance | 0.463    |
| fps                | 3459     |
| nupdates           | 2200     |
| policy_entropy     | 8.58     |
| total_timesteps    | 563200   |
| value_loss         | 0.23     |
---------------------------------
Eval num_timesteps=570000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=580000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.45    |
| explained_variance | 0.545    |
| fps                | 3466     |
| nupdates           | 2300     |
| policy_entropy     | 8.59     |
| total_timesteps    | 588800   |
| value_loss         | 0.17     |
---------------------------------
Eval num_timesteps=590000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=600000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=610000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.43    |
| explained_variance | 0.644    |
| fps                | 3465     |
| nupdates           | 2400     |
| policy_entropy     | 8.64     |
| total_timesteps    | 614400   |
| value_loss         | 0.145    |
---------------------------------
Eval num_timesteps=620000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=630000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=640000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.45    |
| explained_variance | 0.583    |
| fps                | 3463     |
| nupdates           | 2500     |
| policy_entropy     | 8.67     |
| total_timesteps    | 640000   |
| value_loss         | 0.143    |
---------------------------------
Eval num_timesteps=650000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=660000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.42    |
| explained_variance | 0.699    |
| fps                | 3468     |
| nupdates           | 2600     |
| policy_entropy     | 8.67     |
| total_timesteps    | 665600   |
| value_loss         | 0.106    |
---------------------------------
Eval num_timesteps=670000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=680000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=690000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.42    |
| explained_variance | 0.666    |
| fps                | 3466     |
| nupdates           | 2700     |
| policy_entropy     | 8.67     |
| total_timesteps    | 691200   |
| value_loss         | 0.144    |
---------------------------------
Eval num_timesteps=700000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=710000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.4     |
| ep_reward_mean     | -1.45    |
| explained_variance | 0.651    |
| fps                | 3470     |
| nupdates           | 2800     |
| policy_entropy     | 8.66     |
| total_timesteps    | 716800   |
| value_loss         | 0.167    |
---------------------------------
Eval num_timesteps=720000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=730000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=740000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.45    |
| explained_variance | 0.621    |
| fps                | 3469     |
| nupdates           | 2900     |
| policy_entropy     | 8.67     |
| total_timesteps    | 742400   |
| value_loss         | 0.174    |
---------------------------------
Eval num_timesteps=750000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=760000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.43    |
| explained_variance | 0.649    |
| fps                | 3473     |
| nupdates           | 3000     |
| policy_entropy     | 8.68     |
| total_timesteps    | 768000   |
| value_loss         | 0.112    |
---------------------------------
Eval num_timesteps=770000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=780000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=790000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.42    |
| explained_variance | 0.584    |
| fps                | 3472     |
| nupdates           | 3100     |
| policy_entropy     | 8.69     |
| total_timesteps    | 793600   |
| value_loss         | 0.144    |
---------------------------------
Eval num_timesteps=800000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=810000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.42    |
| explained_variance | 0.676    |
| fps                | 3477     |
| nupdates           | 3200     |
| policy_entropy     | 8.7      |
| total_timesteps    | 819200   |
| value_loss         | 0.108    |
---------------------------------
Eval num_timesteps=820000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=830000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=840000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.42    |
| explained_variance | 0.624    |
| fps                | 3474     |
| nupdates           | 3300     |
| policy_entropy     | 8.68     |
| total_timesteps    | 844800   |
| value_loss         | 0.136    |
---------------------------------
Eval num_timesteps=850000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=860000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=870000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.44    |
| explained_variance | 0.624    |
| fps                | 3472     |
| nupdates           | 3400     |
| policy_entropy     | 8.69     |
| total_timesteps    | 870400   |
| value_loss         | 0.169    |
---------------------------------
Eval num_timesteps=880000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=890000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.4     |
| ep_reward_mean     | -1.41    |
| explained_variance | 0.635    |
| fps                | 3475     |
| nupdates           | 3500     |
| policy_entropy     | 8.68     |
| total_timesteps    | 896000   |
| value_loss         | 0.161    |
---------------------------------
Eval num_timesteps=900000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=910000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=920000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 99.4     |
| ep_reward_mean     | -1.42    |
| explained_variance | 0.57     |
| fps                | 3473     |
| nupdates           | 3600     |
| policy_entropy     | 8.69     |
| total_timesteps    | 921600   |
| value_loss         | 0.161    |
---------------------------------
Eval num_timesteps=930000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=940000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.44    |
| explained_variance | 0.66     |
| fps                | 3472     |
| nupdates           | 3700     |
| policy_entropy     | 8.69     |
| total_timesteps    | 947200   |
| value_loss         | 0.143    |
---------------------------------
Eval num_timesteps=950000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=960000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=970000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.43    |
| explained_variance | 0.621    |
| fps                | 3466     |
| nupdates           | 3800     |
| policy_entropy     | 8.69     |
| total_timesteps    | 972800   |
| value_loss         | 0.144    |
---------------------------------
Eval num_timesteps=980000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
Eval num_timesteps=990000, episode_reward=-0.49 +/- 0.00
Episode length: 100.00 +/- 0.00
---------------------------------
| ep_len_mean        | 100      |
| ep_reward_mean     | -1.44    |
| explained_variance | 0.577    |
| fps                | 3469     |
| nupdates           | 3900     |
| policy_entropy     | 8.69     |
| total_timesteps    | 998400   |
| value_loss         | 0.175    |
---------------------------------
Saving to logs/train_1M_widowx_reach-v3/a2c/widowx_reach-v3_1
